### ISSUE TITLE
Rest operator (...) does not correctly transpile for class methods

### ISSUE THREAD

**Issue by Aeomi** [Perryvw/TypescriptToLua#101]
Recently I fixed the rest operator for TSTL, however, I had overlooked class method declaration, where my fix should also be applied.

![image](https://user-images.githubusercontent.com/5202641/39498427-ff121a0e-4d75-11e8-8e15-734bc9445893.png)
![image](https://user-images.githubusercontent.com/5202641/39498468-3b900fae-4d76-11e8-997c-837f8d352647.png)

Where the ```,b``` in the transpilation should be ```,...``` as was fixed [here](https://github.com/Perryvw/TypescriptToLua/issues/95).

**Comment by Perryvw** [comment]
Fixed in 8d9986484f3312a048431ab46534b7e343efacb5
