### ISSUE TITLE
Fix to node.getChildren?

### ISSUE THREAD

**Issue by dsherret** [Perryvw/TypescriptToLua#103]
Hey, neat idea for a project! I was looking at the code in `TSHelper.ts` and saw this comment:

```ts
// Get all children of a node, required until microsoft fixes node.getChildren()
public static getChildren(node: ts.Node): ts.Node[] {
    const children: ts.Node[] = [];
    node.forEachChild((child) => {
        children.push(child);
    });
    return children;
}
```

It made me curious. What do you mean by `required until microsoft fixes node.getChildren()`? Thanks!

**Comment by Perryvw** [comment]
When I first started writing this `node.GetChildren` would return undefined or an empty array even when node.forEachChild was able to find children. This was added as a workaround. 

After a while I kind of figured out `node.getChildren()` can and *should* be avoided if possible, using the proper type casting and properties instead.

I just checked and it seems to be working properly now, so we have even less of an excuse to have this in TsHelper, we should probably try to clean getChildren out of TsHelper altogether though.

**Comment by dsherret** [comment]
Oh ok, that makes sense. I believe `node.getChildren()` only works if the tree is parsed with the option to set parent nodes or if the source file is provided—`node.getChildren(sourceFile)`.

Yeah, `node.getChildren()` will cause an additional parse of the source file text to get the tokens as well (ex. semi-colons) which isn't necessary for your situation (see [here](http://ts-ast-viewer.com) and toggle the option for "tree mode" between `forEachChild` and `getChildren`). Also, you're right that you should be able to get away with just accessing the properties of the nodes and that will be faster.

Anyway, I was just curious because I thought perhaps there was a bug with `node.getChildren()` that I wasn't aware of. Thanks for answering my question!

**Comment by Perryvw** [comment]
Thanks for the heads-up, I'll keep this issue open for now to remind me to clean this up.

**Comment by Perryvw** [comment]
Cleaned up all remaining uses of getChildren in acf4ee0dd6a095bc788253829a5aef43d46d9563
