### ISSUE TITLE
/** !TupleReturn */ does not work on class methods

### ISSUE THREAD

**Issue by andraaspar** [Perryvw/TypescriptToLua#107]
Given a definition:
```TS
declare class Canvas {
	/** !TupleReturn */
	getDimensions(): [number, number]
}
```
And use:
```TS
let c: Canvas
let [w, h] = c.getDimensions()
```
Result:
```lua
-- Generated by TypescriptToLua v0.2.0
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
local c = nil

local w,h=table.unpack(c:getDimensions())
```
Expected:
```lua
-- Generated by TypescriptToLua v0.2.0
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
local c = nil

local w,h=c:getDimensions()
```

**Comment by Perryvw** [comment]
Fixed this (pretty dumb) bug with e138139a3a760f518a6f985fd11f629829998488

**Comment by andraaspar** [comment]
Awesome, thanks! Any chance for a release?

**Comment by Perryvw** [comment]
Was planning on bundling the release with the other issue but since some extra stuff came up I made a quick release and will probably address those other issues in the next release.

**Comment by dasannikov** [comment]
Do not works with static members.
```
/** @tupleReturn */
public static screenToMap(x: number, y: number): [number, number]
```

Compile to table return and unpack method.

**Comment by dasannikov** [comment]
Oh, it works. Need to use `/** !TupleReturn */` bot `/** @tupleReturn */` (as mentioned in wiki)

**Comment by Perryvw** [comment]
Oh my bad I should release that change!

**Comment by Perryvw** [comment]
@dasannikov Just released the version with the new `@` directives, so `@tupleReturn` should work now. I suggest updating your decorations because we might get rid of the `!` ones at some point.
