### ISSUE TITLE
Distinction between dot and colon syntax for methods

### ISSUE THREAD

**Issue by apemanzilla** [Perryvw/TypescriptToLua#108]
Some Lua APIs provide objects with methods that must be invoked using dot syntax (`thing.method(...)`) as opposed to colon syntax (`thing:method(...)`). Having a custom decorator for this would be very useful.

Edit: This behavior already exists for namespaces, it just needs to be expanded for object-oriented use. I propose a new custom decorator, `!DotMethod`, applicable to declarations of classes, interfaces, type literals, and methods of any of these.

Example usages:
```typescript
/** !DotMethod */
declare class SomethingExternal {
	doThing(): SomethingReturned;
}

/** !DotMethod */
interface SomethingReturned {
	doOtherThing(): void;
}

type SomethingElse = {
	/** !DotMethod **/
	dotMethod(): void,
	regularMethod(): void
}
```

**Comment by lolleko** [comment]
You can already use namespaces to accomplish that:

e.g: https://github.com/ark120202/types-lua/blob/master/types/table.d.ts

We should probably mentioned that in the docs somewhere, sorry. I will update the wiki accordingly.

**Comment by apemanzilla** [comment]
Namespaces don't cover everything, though - for example, if you have some function that returns an object with methods that must be called with dot syntax.

**Comment by Perryvw** [comment]
If you declare a method on a class as static it *should* use the dot syntax.

**Comment by apemanzilla** [comment]
That still doesn't help for instance methods that use the dot syntax. Say I have some function that returns an object with methods like so:

```lua
local function getTheObject()
	return { method = function(argument) --[[ do something ]] end }
end

local obj = getTheObject()
obj.method("some argument")
```

There's currently no way to declare this in a way that uses the dot syntax to perform the call.

**Comment by apemanzilla** [comment]
Also, in testing it seems that static methods are still invoked using colon syntax.

**Comment by Perryvw** [comment]
I don't really like the idea of using a decorator for this, feels like there has to be a better way. Will think about it for a bit.

**Comment by apemanzilla** [comment]
For comparison, haxe (4.0+) has an annotation `@:luaDotMethod` which works similarly to the decorator I implemented in #109

**Comment by apemanzilla** [comment]
If you come up with a better alternative, let me know and I'll update my PR.

**Comment by apemanzilla** [comment]
Any changes here? I've been using #109 without issue.

**Comment by Perryvw** [comment]
Contemplating if we could simply use dot methods when the owner of the function is typed as object literal. For example:
```ts
class actualClass {
    literalObject(): { func: () => number } {
        return { func: () => 3 };
    }
}

const instance = new actualClass();
const f = instance.literalObject();
const g = f.func();
```
Translating to
```lua
local f = instance:literalObject()
local g = f.func()
```

Going to run some tests and see how our test suite likes this. Feedback welcome.

**Comment by apemanzilla** [comment]
Is there a reason not to allow them for classes or interfaces?

**Comment by apemanzilla** [comment]
Most of the [ComputerCraft](http://www.computercraft.info/wiki/Main_Page) and [OpenComputers](https://ocdoc.cil.li/) APIs use dot syntax. Using this PR it _should_ be possible to write functional declarations, but there's a few specific cases and potential issues I want to test once I'm at my computer.

**Comment by apemanzilla** [comment]
One idea I had is to use colon methods for traditional functions and dot methods for arrow functions. This maps well to the JavaScript distinction between the two, since arrow functions do not capture `this`, while regular functions do. I'm not sure how feasible this would be to implement based on what's available from the TypeScript compiler, but I think it would provide a relatively clean solution, and would work for complex cases as discussed in #111 without needing another decorator.

**Comment by Perryvw** [comment]
That might actually be quite an elegant solution if we can get this info from the type checker, I will have a look at it later today.
