### ISSUE TITLE
Add Enum.toString() or something similiar 

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#11]
Right now its not possible to use enums as object/table keys.

Possible Fix
```
enum Test {
  file,
  directory,
  link
}

let obj {[name: string]: boolean}

function setValue(value : Test) {
  obj[value.toString()] = true
}

-- In Lua
function setValue(value)
  obj[value] = true
end
```

This would work. But technically its not correct because Test.toString() should return "file", "directory" or "link". With the above solution it would just use the value instead. So this would only work if the enum's values are unique (not sure if thats required by TS or if you can have multiple entries with same values)

**Comment by Perryvw** [comment]
No easy way to do this, I would suggest just making the object key a number type and using value as index instead of value.toString. If you actually need an enum toString (which wont be often) just write the function yourself with a switch or if/else.
