### ISSUE TITLE
Issues using !TupleReturn methods in expressions

### ISSUE THREAD

**Issue by apemanzilla** [Perryvw/TypescriptToLua#113]
`!TupleReturn` now properly works in a sane way for non-destructuring assignment, but it's still not wrapped in a table when used as an expression (e.g. `print(tupleReturnMethod());` or `let a = tupleReturnMethod()[0]`). This brings up the type system discrepancies again, as discussed in #110. Note that for these cases, the return values should be wrapped with `({ ... })` as opposed to simply `{ ... }`, because `{ ... }[1]` is invalid syntax in lua.

**Comment by Perryvw** [comment]
I think this can be solved by moving the tuplereturn checking to the call expression transpilation and traveling up the AST to check if it is part of a destructing assignment. Will have a look probably tomorrow.

**Comment by apemanzilla** [comment]
Alternatively, always wrapping the result in a table and using `select` for destructuring assignments might be easier, but impose a slight performance penalty.

**Comment by Perryvw** [comment]
Should be fixed in 3a92068cddd77a97794c294ba1fa41f37a401554
