### ISSUE TITLE
Invalid syntax when indexing table literals

### ISSUE THREAD

**Issue by apemanzilla** [Perryvw/TypescriptToLua#114]
While testing things related to #113 I found another issue  - currently, code such as `["hello"][0]` is transpiled to `{"hello"}[0+1]`, which causes a syntax error: table literals need to be wrapped with parentheses to be indexed, e.g. `({"hello"})[1]`. This should be a very straightforward fix to `transpileArrayLiteral`.

**Comment by Perryvw** [comment]
Also should be fixed with 3a92068cddd77a97794c294ba1fa41f37a401554
