### ISSUE TITLE
Add support for continue for lua <5.3/JIT

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#118]

**Comment by mitk0936** [comment]
You can easily use coroutines, by  declaring global namespace in your typescript source

Something like:
declare namespace coroutine {
    function create(func: Function): any;
    function yield(...args: any[]): any;
    function resume(...args: any[]): any;
}

**Comment by lolleko** [comment]
Continue was added im #122 and moved to 5.3/JIT in #117 i forgot to close this issue

**Comment by lolleko** [comment]
If you think we should rather implement this with coroutines instead of junp labels feel free to open a new issue

**Comment by mitk0936** [comment]
It wasnt the right place to add the comment.

I had issues with using coroutines with the transpiler and I thought this issue is related.

Anyways, keep it up with the good work
