### ISSUE TITLE
Fix typescript overload

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#122]
https://www.typescriptlang.org/docs/handbook/functions.html#overloads
TS overloads are basically syntax sugar for `function(x : TypeOne | TypeTwo)`. So there should be no problem when allowing them.

For that we need to ignore funciton declarations.

```
function pickCard(x: {suit: string; card: number; }[]): number; // ignore
function pickCard(x: number): {suit: string; card: number; };   // ignore
function pickCard(x): any {                                     // transpire only functions with body
    // Body....
}
```

**Comment by Perryvw** [comment]
Done in #128
