### ISSUE TITLE
Can't seem to define a Lua method in a .d.ts file?

### ISSUE THREAD

**Issue by osyrisrblx** [Perryvw/TypescriptToLua#133]
A game engine I use creates global variables in Lua which are instances of objects. As such, I need to call functions on these objects as methods instead of normal functions.

Is there a way to denote this in a .d.ts file so that the transpiler understands it?

```TypeScript
// Foo.d.ts
declare abstract class Foo {
	Bar: () => {};
}

declare const foo: Foo;
```

```TypeScript
// main.ts
foo.Bar();
```

```Lua
-- main.lua
foo.Bar()
```

tl;dr: How do I make the transpiler do `foo:Bar()` instead of `foo.Bar()`

**Comment by osyrisrblx** [comment]
I was using the wrong syntax for my .d.ts it should have been:

```TypeScript
declare abstract class Foo {
	Bar(this: Foo): {};
}

declare const foo: Foo;```

Sorry!

**Comment by Perryvw** [comment]
Just  `Bar(): {}` will do, the `this` is automatically added. That other syntax is specifically for properties you call with . as you noticed.
