### ISSUE TITLE
Runtime Library should only be imported for files which require it.

### ISSUE THREAD

**Issue by osyrisrblx** [Perryvw/TypescriptToLua#134]
If a file contains no references the Runtime library (Set, Map, Array.push, etc.), the library should not be required.

**Comment by lolleko** [comment]
I think we discussed that a while back, while this is certainly possible it requires quite a bit of implementation work. So we decided that for now we stick with either include it everywhere or not at all. We might add conditional runtime lib requires in the future but it doesn't have a high priority. If you want to make a PR for this, that would be awesome.

You can disable the import via `dontRequireLuaLib: true` in your tsconfig.json.

**Comment by lolleko** [comment]
Possible Implementation:

Have a flag (bool) inside LuaTranspiler that is false by default. If a feature is used that requires the runtime lib, set that flag to true and prepend `require("typescript_lualib")` to the output after the main transpileBlock in transpileSourceFile is completed.

**Comment by Perryvw** [comment]
This is a matter of cost in development time and possible bugs vs. possible gains (which I don't really see right now).
