### ISSUE TITLE
How to deal with built-in Lua functions which return multiple values?

### ISSUE THREAD

**Issue by osyrisrblx** [Perryvw/TypescriptToLua#135]
TypeScript has the concept of functions which return tuples but TSTL treats these functions as returning tables and then performs unpack() on the result.

For functions not written in TS (built-in to Lua), we can't change them to return arrays of arguments (tables) without wrapper functions.

Is there a better way to handle this?

**Comment by Perryvw** [comment]
Check out our [Wiki](https://github.com/Perryvw/TypescriptToLua/wiki/Custom-Decorators#tuplereturn)!
