### ISSUE TITLE
The nil in Lua does not calculate the length

### ISSUE THREAD

**Issue by imfox** [Perryvw/TypescriptToLua#149]
```typescript
let x:number[] = [null,null,null,null];
print(x.length) //4
```
```lua
local x = {nil,nil,nil,nil}
print(#x)  -- 0
```
The nil in Lua does not calculate the length

**Comment by Perryvw** [comment]
I don't think this is even something we can fix, this is just how lua `#` works.

**Comment by lolleko** [comment]
Maybe we could define our own null/undefined somewhere, but that might cause other issues or doesnt really work

**Comment by Perryvw** [comment]
The question is if something like that is worth the effort. In my opinion this is a case of [KISS](https://en.wikipedia.org/wiki/KISS_principle).

**Comment by osyrisrblx** [comment]
`null` in Lua is much closer to `undefined` than `null`.

**Comment by Perryvw** [comment]
Will close this for now, maybe we can revisit later.
