### ISSUE TITLE
Improve module system

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#15]
Right now all classes are in the global scope. I dont think this is ideal if you work with many different modules/classes.
The Transpiler should probably convert the export / export default keyword to a return statement. [Lua module system](http://lua-users.org/wiki/ModuleDefinition).
```
export default class SomeClass {
  ...
}
```

=>

```
local SomeClass = SomeClass or {}
SomeClass.__index = SomeClass
function SomeClass.new(construct, ...)
    local instance = setmetatable({}, SomeClass)
    if construct and SomeClass.constructor then SomeClass.constructor(instance, ...) end
    return instance
end

...

return SomeClass
```

that way you could require it like this in lua/ts

```
local SomeClass = require("some_class")
```

**Comment by Perryvw** [comment]
`export default` causes classes to be returned as of 4f1fd4188fc60641f8f11ac20d8a86604eb4ab50
