### ISSUE TITLE
How to change Lua's require path in case of changing a outDir path in tsconfig?

### ISSUE THREAD

**Issue by ProgrammingLife** [Perryvw/TypeScriptToLua#1524]
I've changed an `outDir` path in .tsconfig but my `require( ... )` path are stay the same in generated Lua code as it was before changing `outDir`.
How do I synchronize these two path?

**Comment by Perryvw** [comment]
Depends how your require paths are added to your code. If they are regular TS imports that are resolved normally, the path should point to the lua files present in the outDir. If you are using noResolve paths you are essentially avoiding the TSTL path logic and it's your own responsibility to make sure the paths are correct.
