### ISSUE TITLE
Add Map/Set to lualibfeatureset if used

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#154]
Possible places to check if map/set is used: 
* `transpileNew`: this might not work if map/set is used in an external library that doesn't do inlining.
* `transpileVaraibleDeclaration` will this cover all cases?
* `transpileNew` + object access: (function call or property access to Maps/Sets) should guarantee that Map/Set is inlined when used somewhere

We should probably also implement it in a way we can easily add other JS internal classes.

**Comment by Perryvw** [comment]
To append the list of possibilities:
- Check property calls and new calls
- Traverse entire the tree and inspect types

Or (preferably not)
- Don't support map/set with inlining
