### ISSUE TITLE
luaTarget: "5.1" polyfills

### ISSUE THREAD

**Issue by Janne252** [Perryvw/TypescriptToLua#157]
Hey,

Since the generated lua code may contain features that are not present in Lua 5.1, there might be a need for Lua polyfills, namely the `table.pack` and `table.unpack` methods (of which neither are available in Lua 5.1).

For example
```ts
// zoo() actually returns an array we want to unpack. 
// Otherwise we could use /** !TupleReturn */ decorator!
let [foo, bar] = zoo();
```
Results in
```lua
local foo,bar=table.unpack(zoo())
```

Which won't work in a strict Lua 5.1 environment.

#### table.pack
```lua
if not table.pack then
    function table.pack (...)
        return {n=select('#',...); ...}
    end
end
```
Source: https://github.com/stevedonovan/Penlight/blob/master/lua/pl/compat.lua#L133

#### table.unpack
```lua
if not table.unpack then
    function table.unpack(...)
        return unpack(...)
    end
end
```

**Comment by lolleko** [comment]
#141 this was already in a PR here. PR didn't get merged because of missing tests.

**Comment by Perryvw** [comment]
Closing this after the merge of the PR in bc073bb9d0144e1425fdc2bf5dcffca967861fc0
