### ISSUE TITLE
Disallow using Lua keywords as names

### ISSUE THREAD

**Issue by nucleartide** [Perryvw/TypescriptToLua#171]
From https://www.lua.org/manual/5.1/manual.html:

```
The following keywords are reserved and cannot be used as names:

     and       break     do        else      elseif
     end       false     for       function  if
     in        local     nil       not       or
     repeat    return    then      true      until     while
```

**Comment by Perryvw** [comment]
Duplicate of #47, we can actually do this now because we recently refactored to transpileIdentifier.

**Comment by Perryvw** [comment]
Thought I just had: Different versions of Lua might use different keywords, so that should be kept in mind when implementing this.

**Comment by Perryvw** [comment]
Adressed with d63ce0365c509ba4819b20220acccaaa1bfb27e8.
