### ISSUE TITLE
for in loop adds +1 to loop variable

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#18]
```
for (const y in list) {
     list[y]
}
```
=>
```
for y, _ in ipairs(list) do
   list[y+1]
end
```

**Comment by Trildar** [comment]
Why would you use `for...in` on an array anyway?

**Comment by lolleko** [comment]
Its not that I want to do it. But it is allowed/works in js/ts therefore I expect it to work aswell in ts->lua. It should just work or according to specs, or throw an exception, that warns me that my code won't work as expected (that `for in` on arrays is not allowed).

**Comment by Perryvw** [comment]
Just throwing an exception if `for ... in` is used on a loop seems to be me best option here. I don't really feel like going out of my way just to allow bad practice.
