### ISSUE TITLE
Typescript 3

### ISSUE THREAD

**Issue by gakada** [Perryvw/TypescriptToLua#184]
I tried updating to `typescript@3` and there is two problems, both with `getCombinedModifierFlags`.

https://github.com/Perryvw/TypescriptToLua/blob/f62835e9d86ca09ec64c585c063d799d8e0e9f90/src/Transpiler.ts#L121

`Node` vs expected `Declaration`, can use `as Declaration` here?

https://github.com/Perryvw/TypescriptToLua/blob/f62835e9d86ca09ec64c585c063d799d8e0e9f90/src/TSHelper.ts#L51

not sure what to do here.

**Comment by lolleko** [comment]
TS 3 is on our todo list. Not sure we can just cast there, but im sure its fixable.

**Comment by lolleko** [comment]
This is delayed due to bugs in Typescript 3.0 you can track the progress here #247
