### ISSUE TITLE
Operation order is not always respected

### ISSUE THREAD

**Issue by gakada** [Perryvw/TypescriptToLua#185]
For example
```ts
const t7 = (i: number) => '12345'.charAt((i < 3 && 2) || 4)
```
gives
```lua
local t7 = function(i) return string.sub("12345",((i<3) and 2) or 4+1,((i<3) and 2) or 4+1) end
```
because there is missing brackets here

https://github.com/Perryvw/TypescriptToLua/blob/f62835e9d86ca09ec64c585c063d799d8e0e9f90/src/Transpiler.ts#L1120-L1161

probably all those functions are affected.

**Comment by gakada** [comment]
`t7(2)` gives `3` in TypeScript but `2` in Lua.

`((i<3) and 2) or 4+1` that should be `(((i<3) and 2) or 4)+1`, etc.

**Comment by Perryvw** [comment]
Ah I see, that indeed seems to be a bug with missing parantheses.
