### ISSUE TITLE
Recursion doesn't work with arrow functions

### ISSUE THREAD

**Issue by gakada** [Perryvw/TypescriptToLua#187]
Input
```ts
const f = (i: number): number => (i <= 1 ? i : i * f(i - 1))
```
Output
```lua
local f = function(i) return (__TS__Ternary(i<=1, function() return i end, function() return i*f(i-1) end)) end
```

**Comment by gakada** [comment]
I think for Lua any recursion
```lua
local f =  function(...)
  ... using f
end
```
won't work?

So maybe all (`const`?) assignments to functions should produce `local function`.

**Comment by Perryvw** [comment]
Yes I think it doesn't work if you use `=` instead of `local function`, I will add a quick check to see if the initializer type is a function, and we will find out the edge cases where this breaks quick enough I guess.
