### ISSUE TITLE
Parameter property shorthand in class constructors

### ISSUE THREAD

**Issue by Trildar** [Perryvw/TypescriptToLua#2]
As detailed here: https://www.typescriptlang.org/docs/handbook/classes.html

Currently doesn't transpile such shorthand, resulting in the constructor not assigning properties as expected.
For example, a constructor function, `constructor(public A: string) {}`, would transpile to a constructor function with an empty body.

**Comment by Perryvw** [comment]
Implemented in commit d456030d248811ec7df6d7678e1491d6738b08be

**Comment by Trildar** [comment]
I meant that the transpiler at the time was outputting an empty body. Not that it should work that way. Guess the wording was kinda ambiguous.
