### ISSUE TITLE
Invalid lua produced when destructuring into existing variables

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#200]
```ts
/** !TupleReturn */
declare function foo(): [string, number];
let [s, n] = foo();
[s, n] = foo();
```

Produces:
```lua
local s,n=foo();
{s,n} = ({ foo() }); --lua5.1: unexpected symbol near '{'
```

So basically, destructuring to variables when they are declared with let works, but destructuring into those variables again later produces invalid lua code.

**Comment by tomblind** [comment]
I just realized this same problem occurs without !TupleReturn as well. So, it seems to be a bug with destructuring to existing vars in general.

```ts
declare function foo(): [string, number];
let [s, n] = foo();
[s, n] = foo();
```

```lua
local s,n=unpack(foo());
{s,n} = foo();
```

**Comment by lolleko** [comment]
Seems like we only check for destructuring/tuples in variable declarations. we should probably add the same logic to transpileAssignment aswell.
