### ISSUE TITLE
Function scoping inconsistent between ts and lua

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#201]
In Typescript/Javascript, when a function is declared inside of another, it is local to that function. But currently in the output lua, it will be global. This has subtle implications in how the code will run and can cause unexpected bugs.

Consider this:
```ts
function a() {
    function foo() {
        return "a";
    }
}

function b() {
    function foo() {
        return "b";
    }
    a();
    console.log(foo());
}

b();
```

Which produces:
```lua
function a()
    function foo()
        return "a"
    end
end
function b()
    function foo()
        return "b"
    end
    a();
    console:log(foo());
end
b();
```

When compiled and run as javascript, this will output "b", but the lua will output "a" because the definition of foo will be overridden.

I would suggest adding "local" to all functions declared inside of others to keep the logic consistent with how the typescript would work.

**Comment by tomblind** [comment]
Putting some more thought into this, there's situations where top-level functions should also be marked local, in order to be consistent with typescript.

Specifically, functions which are:
- Stand-alone
- Not exported
- Part of a module (any ts file with top-level export or import statements)

This will ensure they do not override each other if multiple modules define the same function.

**Comment by Perryvw** [comment]
I do not like the idea of making top-level functions local since after translation they will no longer be callable across required lua files if I remember correctly.

**Comment by tomblind** [comment]
Yes, in lua top-level functions marked local are scoped to the module and inaccessible outside of it. I'm suggesting this so that it mirrors functionality in typescript.

Consider this example:
``ts
//ModuleA.ts
function foo() {
    console.log("A");
}

export function funcA() {
    foo();
}

//ModuleB.ts
function foo() {
    console.log("B");
}

export function funcB() {
    foo();
}

//Main.ts
import {funcA} from "ModuleA";
import {funcB} from "ModuleB";
funcB(); //prints "B" in TS but "A" in lua
```

In TS, the two foo implementations are not accessible from outside and do not conflict with each other. Calling funcB would print "B" as expected. But in lua, importing ModuleB would override ModuleA's foo implementation and funcB would print "A". In a more complex situation, you can see how this would cause some subtle, but chaotic bugs.

**Comment by lolleko** [comment]
We should declare top level local if modules (import/export) is used in any file. I think TS does something similiar, if no module mechanism is used everthing is declared in global scope.
