### ISSUE TITLE
Error exporting namespace

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#209]
It seems I can't export a namespace which exports any variables/functions:

```ts
export namespace Foo
{
    export const bar = "bar";
}
```
Produces:
```lua
local exports = exports or {}
local Foo = Foo or {}
do
    local bar = "bar";
    exports.Foo.bar = bar --attempt to index field 'Foo' (a nil value)
    Foo.bar = bar
end
exports.Foo = Foo
return exports
```

Which throws an error as soon as it's imported due to exports.Foo being accessed before being assigned.

**Comment by lolleko** [comment]
This is also related to #207 we changed the export mechanism to export values at the end of a block. Seems like this doesn't work very well with namespaces.

**Comment by lolleko** [comment]
The the issue in the second comment isn't that important imo. Since you TS won't allow you to access `bar` since it was not exported. This will only cause issues if you import `Foo` and access `bar` via `(Foo as any).bar`

**Comment by tomblind** [comment]
Good point - definitely not a serious issue. I can imagine extreme edge cases where someone might iterate members of the namespace and get more than they expect, though.

**Comment by tomblind** [comment]
What is the purpose of exporting twice here:
```ts
    exports.Foo.bar = bar
    Foo.bar = bar
```
The assignment to exports seems redundant, doesn't it? Also, it's added even if the namespace is not exported:
```ts
export interface ForceModule {};

namespace Foo
{
    export const bar = "bar";
}
```
```lua
local exports = exports or {}

local Foo = Foo or {}
do
    local bar = "bar";
    exports.Foo.bar = bar --should not be exported
    Foo.bar = bar
end
return exports
```

It seems like it's not needed at all. Or am I missing a case where it would be necessary?

**Comment by lolleko** [comment]
The problem is that you need to duplicate the namespace if not all members are exported. This used to work. But i think we just  removed/changed some of that functionality accidentially.

If irrc it used to be like this:

```
namespace Foo
{
    export const bar = "bar";
    const baz = 3;
}
```
```
local Foo = Foo or {}
exports.Foo = exports.Foo or {}
do
    local bar = "bar";
    exports.Foo.bar = bar
    Foo.bar = bar
    local baz = 3
    Foo.baz = baz
end
return exports
```

**Comment by tomblind** [comment]
> The problem is that you need to duplicate the namespace if not all members are exported.

My apologies, I'm not totally sure what you mean here.

In an attempt to wrap my head around this, I took a look at the JS that tsc generates:
```js
var Foo;
(function (Foo) {
    Foo.bar = "bar";
})(Foo = exports.Foo || (exports.Foo = {}));
```
In lua that would basically be this:
```lua
local exports = exports or {}
local Foo = exports.Foo or {}
exports.Foo = Foo
do
    Foo.bar = "bar"
end
return exports
```

Since Foo should always be the same object as exports.Foo, there doesn't seem to be a need to do the assignment 'exports.Foo.bar = "bar"'.

**Comment by lolleko** [comment]
No you are actually right, JS doesn't duplicate the namespace.

```
"use strict";
exports.__esModule = true;
var test;
(function (test) {
    var x = 3;
    test.y = 21;
})(test = exports.test || (exports.test = {}));
console.log(exports.test === test);
```
prints true for me.

`(test = exports.test || (exports.test = {}))` basically translates to 
```
if (exports.test) {
  test = exports.test;
} else {
  exports.test = {}
  test = exports.test; // since (exports.test = {}) returns the result of the assignment which is exports.test
}
```
So yeah we should make the changes you suggested.

The reason why I thought it needed to be duplicated is because I thought you could access namespaces members inside the same file regardless if they are exported or not.
```
namespace x {
 const y = 12;
}
const z = x.y;
```
turns out you can't do that so there is no reason to keep an extra table.

**Comment by tomblind** [comment]
Ah, ok! My knowledge of JS/TS is much less than that of lua, so I thought I there was something I wasn't aware of going on here.

I'll take a look at doing a fix for this since it's a bit of a blocker for me right now.
