### ISSUE TITLE
Referencing 'this' in arrow function assigned to class property produces bad reference in lua

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#213]
```ts
class Foo
{
    public method() {}
    public propMethod = () => { this.method(); }
}
const foo = new Foo();
foo.propMethod();
```
produces:
```lua
Foo = Foo or {}
Foo.__index = Foo
function Foo.new(construct, ...)
    local instance = setmetatable({}, Foo)
    instance.propMethod = function()
    self:method(); --attempt to index global 'self' (a nil value)
end

    if construct and Foo.constructor then Foo.constructor(instance, ...) end
    return instance
end
function Foo.constructor(self)
end
function Foo.method(self)
end
local foo = Foo.new(true);
foo.propMethod();
```

It seems like the simple fix would be to rename 'instance' to 'self'.

**Comment by lolleko** [comment]
I think the better fix would be to move declaration of arrow functions from the `.new()` function to the rest of the methods.

**Comment by tomblind** [comment]
Like this?
```lua
Foo.propMethod = function(self) self:method() end
```
But then self wouldn't be captured as it would in typescript. It would have to be called with a colon instead of a dot, which I've read in other discussions here was intended by design as a way to distinguish methods for apis that use dot syntax.

**Comment by Perryvw** [comment]
If I remember correctly we added shit syntax specifically for defining dot calls on interfaces. Therefore I don't think adding self as a parameter would work. What would maybe work is to define `local self = instance` in `new()` before the function definitions, that way the instance would be captured in scope? Let me know what you guys think.

**Comment by tomblind** [comment]
That would work. I was just trying to cut out the extra local by suggesting the rename.
