### ISSUE TITLE
Multiple variable declarations in single statement produces malformed lua

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#217]
```ts
let a = 1, b = 2, c = 3;
```
=>
```lua
local a = 1local b = 2local c = 3;
```

**Comment by tomblind** [comment]
I think putting a semicolon ';' at thend of variable assignments would fix this without complications.

**Comment by tomblind** [comment]
Nevermind. I tried putting semicolons in, but it produces a double semicolon ';;' at the end of the line which is explicitly illegal in lua.

Seems like adding whitespace is the only simple option.

**Comment by Perryvw** [comment]
Adding a newline after each assignment is probably the nicest solution here.

**Comment by tomblind** [comment]
Realized the place I was trying to put the semi-colon was bad. The PR has a 'proper' fix that puts each declaration on its own line with a semi-colon.
