### ISSUE TITLE
Issues with non-lua operators on properties of objects

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#221]
Operators such as '+=', '++', etc... can be broken easily right now.

Example 1:
```ts
declare function foo(): number;
declare const a: number[];
a[foo()]++;
```
=>
```lua
a[(foo())+1] = (a[(foo())+1]+1);
```
Here foo() will be called multiple times, producing possibly different values each time or having other undesired side-effects.

Example 2:
```ts
declare function bar(): number[];
let f = bar()[0]++;
```
=>
```lua
local f = (function()
    local __originalValuebar()[(0)+1]0 = bar()[(0)+1];
    bar()[(0)+1] = (bar()[(0)+1]+1);
    return __originalValuebar()[(0)+1]0
end
)();
```
This one won't even compile in lua.

These kinds of issues could be solved by detecting if the value being operated on is a property and caching the object and index parts before performing the operation. This could be wrapped in specialized polyfill functions like the ternary operator is:
```lua
function __TS__PropertyPostInc(o, i)
    local original = o[i]
    o[i] = o[i] + 1
    return original
end

--Example 1
__TS__PropertyPostInc(a, foo())

--Example 2
local f = __TS__PropertyPostInc(bar(), 0)
```

**Comment by Perryvw** [comment]
Looks like a tricky issue indeed. We would have to polyfill all(?) unary and [binary assignment operators](https://github.com/Perryvw/TypescriptToLua/blob/master/src/TSHelper.ts#L142) to have this work properly? I feel like it might be nicer to find an inline solution if possible, but I will have to think about this for a bit.

**Comment by tomblind** [comment]
Yes, all of them would have to be covered. Using polyfills is more efficient however, since the inline solution requires generating a temp lambda every time (at least for expressions).

**Comment by tomblind** [comment]
Of course, to be clear, it is possible to do this inline as well (just less efficient). I definitely can understand the desire to avoid excessive polyfills.

```lua
(function(o, i) local original = o[i]; o[i] = original + 1; return original)(a, foo())

local f = (function(o, i) local original = o[i]; o[i] = original + 1; return original)(bar(), 0)
```

**Comment by lolleko** [comment]
why do you need that extra function call? couldnt we just use:
```
a[foo()]++;
````

```
local ___propertyIndex1 = foo(); a[___propertyIndex1 ] = a[___propertyIndex1 1] + 1;
```
and to make `let f = bar()[0]++;` work extend it further:
```
local ___propertyIndex1 =0;
local ___temp1 = bar();
___temp1 [___propertyIndex1 ] = ___temp1 [___propertyIndex1] + 1;
```

But thats pretty ugly so it might be petter to polyfill.
In either case we should probably add a compile time warning about shorthand assignements/operators affecting performance.

**Comment by tomblind** [comment]
You're right, the first example doesn't require a function. The second example currently compiles to a function to allow it to be evaluated as an expression (to avoid issues in different scenarios: see #162 discussion). I assume it would be best to keep it that way.

**Comment by lolleko** [comment]
Well, poylfilling is fine wiht me than, at least for now. If we can think of a better/faster inline solution we can still add it later. Maybe we can check if there is a function call inside the shorthand operation and only polyfill in that case....

But we should defintly add a warning because a polyfilll will make a simple increment pretty expensive.

**Comment by tomblind** [comment]
A function call check wouldn't work in all cases is setters/getters are implemented via metatables as proposed in #206 - there'd be no way to know if a simple property access was actually calling a function or not.

I wouldn't argue against a warning, although it would be good to be able to disable it (maybe via a decorator?).

**Comment by Perryvw** [comment]
I think using polyfills would probably be 'easiest' for now. Better than having incorrect behavior for sure. (ignoring the debate that using a function that modifies state as index is probably a terrible name)

**Comment by tomblind** [comment]
> ignoring the debate that using a function that modifies state as index is probably a terrible name

Oh, it's definitely terrible. But I've seen it in enough code to know it should probably be accounted for.

I suggest using an inline solution for statements and a polyfill for expressions. That would be most efficient for each scenario without breaking things. I suspect using these operators as expressions is far less common so that would limit the polyfill usage a lot.
