### ISSUE TITLE
NonNullExpression could be implemented

### ISSUE THREAD

**Issue by cymerrad** [Perryvw/TypescriptToLua#224]
Sometimes I'm sure that some key-value pairs exist in a map, so I'm using "!" to get around compiler/linter yelling at me, that the value I'm getting from this map may be undefined.

```Typescript
declare function print(...msg: any[]): void;

type OnlyPossibleValues = "a" | "b" | "c";
let valueToNumber: Map<OnlyPossibleValues, { property: number }> = new Map();
valueToNumber.set("a", { property: 1 });
valueToNumber.set("b", { property: 2 });
valueToNumber.set("c", { property: 3 });

// let possiblyDefinedValue = valueToNumber.get("a");
let definitelyDefinedValue = valueToNumber.get("b")!;
// print(possiblyDefinedValue.property);
print(definitelyDefinedValue.property);
```

Unfortunately this is not implemented, even though it wouldn't have any effect on Lua code, but it would improve working with Typescript.

**Comment by lolleko** [comment]
Your issue is about typescript/tslint, I don't think what you are suggesting is in the scope of this project. You can just disable those warnings if they annoy you.

Or maybe I a not understanding you correctly. Could you clarify what you want us to implement?

**Comment by Perryvw** [comment]
NotNullExpression is actually a typescript expression `expression!` which basically denotes the expression will not be null. Seems to be an oversight, the only implementation here is to just transpile the containing expression since it is a typechecker-only thing.
