### ISSUE TITLE
luajit target should not use table.unpack

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#238]
LuaJIT still uses 'unpack' from lua5.1; it does not support 'table.unpack', which is what tstl uses for the 'jit' target right now.

**Comment by tomblind** [comment]
I believe there was a mis-understanding here. The fix still has the jit target using 'table.unpack', but luajit uses the standalone 'unpack' function, just like lua 5.1.

**Comment by adriweb** [comment]
> I believe there was a mis-understanding here. The fix still has the jit target using 'table.unpack', but luajit uses the standalone 'unpack' function, just like lua 5.1.

Indeed, although if compiled with `LUAJIT_ENABLE_LUA52COMPAT` luajit has table.unpack and unpack aliased. But I guess `unpack` should be preferred as it's really 5.1-like.

**Comment by Perryvw** [comment]
Whoops, too much of a hurry from me there.
