### ISSUE TITLE
Unpacking return values?

### ISSUE THREAD

**Issue by Subtixx** [Perryvw/TypescriptToLua#24]
So I created typescript definitions for MTA:SA (A multiplayer mod for GTA:San Andreas). I'm fairly new to typescript so excuse me if I did something wrong.

This is my function declaration:
```ts
declare function getElementPosition(theElement: element): [number, number, number]
```

This is how I use it:
```ts
let [pX, pY, pZ] = getElementPosition(player);
```

Example from the wiki says:
```lua
local x,y,z = getElementPosition( myElegy )
```
https://wiki.multitheftauto.com/wiki/GetElementPosition

But the transpiler is making this:
```lua
local __destr0 = getElementPosition(player)
local pX = __destr0[1]
local pY = __destr0[2]
local pZ = __destr0[3]
```

which results in the error "attempt to index local '__destr0' (a number value)

**Comment by Subtixx** [comment]
Hmm figured as much :/. Thanks for the heads up though. Maybe I'll modify it then, since in Lua there is no native "array" but a table, which is already implemented (In my local copy) with native lua type definitions.

**Comment by Perryvw** [comment]
Sounds like a custom decorator for the function declaration would be ideal here.

**Comment by Perryvw** [comment]
Added the `/** !TupleReturn */` decorator in 04dc05bcbcc647df84160b35125c58b1a144be5e. Add this to your declarations:
```typescript
/** !TupleReturn */
declare function getElementPosition(theElement: element): [number, number, number]
```
And call the function as before:
```typescript
let [pX, pY, pZ] = getElementPosition(player);
```
This should cause the code to be translated exactly to the example you gave:
```typescript
local x,y,z = getElementPosition( myElegy )
```

Let me know if you have any issues!

**Comment by felixhirt** [comment]
This does not work for me:

/** !TupleReturn */
function dostuff(value:string) : [string, number] {
    return ["string",42];
}

let [a,b] = dostuff("param");

transpiles to:

function dostuff(self, value)
    return {"string", 42}
end
a, b = table.unpack(
    dostuff(nil, "param")
)

do i need to configure this somehow? Or is the code not correct?

**Comment by Perryvw** [comment]
Hi @felixhirt, this is a very old thread, our annotations syntax has changed since then (to follow jsDoc convention). Try replacing `/** !TupleReturn */` with `/** @tupleReturn */` ;)

**Comment by felixhirt** [comment]
thank you very much... guess i should have read the docs instead of an old issue ;-). google brought me here :-(
