### ISSUE TITLE
Figure out how to support operator overloads

### ISSUE THREAD

**Issue by Perryvw** [Perryvw/TypescriptToLua#246]
Lua allows operator overloads and several API's provide type-overloaded objects such as vectors in DotA. It would be nice if we could find a way to support declarations of type overloaded objects. For example:
```ts
class Vector {
    constructor(public x: number, public y: number) { }
    // Overloading + operator
    public __add(other: Vector): Vector {
        return new Vector(this.x + other.x, this.y + other.y);
    }
}
```
Would be nice if we could then do:
```ts
const v1 = new Vector(2,3);
const v2 = new Vector(4,5);
const v3 = v1 + v2;
```

Unfortunately since JavaScript does not support operator overloading, there is no good way to declare this in TypeScript. Operator overloads are very useful however, and it would be nice if we could support them somehow.

**Comment by tomblind** [comment]
The real issue here is the '+' syntax. Typescript is pretty strict about this and short of using some really hacky type assertion stuff, I don't believe it's possible without modifying TS itself.
```ts
let a = new Vector(1, 2);
let b = new Vector(3, 4);
type V = Vector & number;
let c = <V>(<V>a + <V>b);
```

But if the goal is to support external code that uses overloads, declaring a custom function that 'magically' gets converted to the correct operator could be a way to go.
```ts
interface Addable<O, R = O> {
    __add(other: O): R;
}

declare function $add<O, R>(a: Addable<O, R>, b: O): R;

declare class Vector implements Addable<Vector>, Addable<number, Vector> {
    public constructor(x: number, y: number);
    public __add(other: Vector): Vector;
    public __add(other: number): Vector;
}

let a = new Vector(1, 2);
let b = new Vector(3, 4);
let c = $add(a, b);
let d = $add(a, 7);
```
```lua
local a = Vector.new(true,1,2);
local b = Vector.new(true,3,4);
local c = (a+b);
local d = (a+7);
```

**Comment by Perryvw** [comment]
yeah the issue is typescript here, and not the translation. This is a pretty common issue encountered when encountering declarations. Would be nice if we could come up with some kind of convention to deal with this. One hack I use is to indeed define `type Vector = number` which allows the use of operators, but then other properties are an issue. Your type intersection looks interesting, I will look into that.

**Comment by tomblind** [comment]
The big problem with the intersection is the result of any '+' will be typed as a number, not the intersection type. So it has to be cast back again.
```ts
type V = Vector & number;
declare a: V;
declare b: V;
let c = a + b; //typeof c == number
let d: V = a + b; //error: cannot assign number to V
let e = <V>(a + b); //the only way
```

**Comment by lolleko** [comment]
The best workaround i found so far is casting one(or both) operand to any and then back to the original type after calculation. But this also doesnt work in every case.

I think we can only properly implement overloading if TS adds support for it (but they already said the wont do it unless JS does it aswell). We could create a fork of TS and add it ourselves, but that would be a lot of work and hard to maintain

**Comment by Perryvw** [comment]
Yes I would prefer not to have to maintain TypeScript ourself. I am actually pretty happy with the intersection type @tomblind suggested, it does still require some casting but much less, it is certainly much better than the current 'type Vector = number' hack used in the DotA declarations.

**Comment by Perryvw** [comment]
Documented the workaround on the wiki:
https://github.com/Perryvw/TypescriptToLua/wiki/Writing-Declarations#operator-overloads

Closing this since we can not do anything else about this for now.
