### ISSUE TITLE
'this' binding and dot vs colon

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypeScriptToLua#250]
I've found a couple of issues with transpiling functions and dealing with 'this'.

Example 1:
```ts
interface Foo {
    bar(s: string): void;
}
const o: Foo = {
    bar: (s: string) => print(s)
}
o.bar("foo");
```
```lua
local o = {bar = function(s) return print(s) end};
o:bar("foo"); --prints "table: 00709330"
```
Here, the colon is mistakenly used because the interface declares the function as a method, but the implementation creates it as an arrow function. This is a tough issue to solve since there's no way to know for sure which operator to use at the call site.

Example 2:
```ts
class C {
    private prop = "foo";
    public outer() {
        const o = {
            prop: "bar",
            innerFunc: function() { print(this.prop); },
            innerArrow: () => print(this.prop)
        };
        o.innerFunc(); //Should print "bar"
        o.innerArrow(); //Should print "foo"
    }
}
let c = new C();
c.outer();
```
```lua
C = C or {}
C.__index = C
function C.new(construct, ...)
    local self = setmetatable({}, C)
    self.prop = "foo"
    if construct and C.constructor then C.constructor(self, ...) end
    return self
end
function C.constructor(self)
end
function C.outer(self)
    local o = {prop = "bar",innerFunc = function()
        print(self.prop);
    end
,innerArrow = function() return print(self.prop) end};
    o.innerFunc(); --Incorrectly prints "foo"!
    o.innerArrow();
end
local c = C.new(true);
c:outer();
```
Here the inner function incorrectly captures self from the outer method.

I suspect there's probably a lot of other similar edge cases around. They all boil down to inconsistencies with how JS handles 'this' binding.

As I understand it, in JS, all functions have a 'this', which is whatever was on the left side of the dot when called. The 2 exceptions are arrow functions and stand-alone functions (ones with no left-side to bind). Arrow functions capture the 'this' from their outer scope and stand-alone functions have the global scope (window) as their 'this'.

I believe the solution is to re-work how functions are transpiled overall to mirror that behavior:
- All functions should be given an initial 'self' parameter
- Arrow functions should name this first parameter with a dummy name ('_') so they capture the self of their outer scope
- All functions (except stand-alone) should be called with colon syntax
- Stand alone functions should (maybe?) pass _G as their first parameter

With this setup, all lua functions would have a self that mirrors 'this' from the equivalent JS. Plus, there would be no need to decide whether to use dot or colon as all calls would use colon.

The one case this doesn't handle is functions from external sources that need to be called with dot syntax. A decorator would probably be the way to handle this. I know that was shot down before (see #108), but I think it's worth reconsidering.

Thoughts?

**Comment by tomblind** [comment]
Agreed. There's undoubtedly more edge cases we'll come across.

Static functions actually use colon syntax now, for exactly this reason, so they don't need to change.

bind could be implemented with something like this:
```lua
function __TS_bind(func, obj)
    return function(_, ...) func(obj, ...) end
end
```
Probably apply could be done similarly.

**Comment by Perryvw** [comment]
Made a new branch to experiment on https://github.com/Perryvw/TypescriptToLua/compare/new-functions
with some tests for apply and bind. The tests are currently failing on this branch. We can try some stuff on there the coming days to figure out how to best do this. Will be lenient on PRs to that branch, we can clean up once we settle on something

**Comment by ark120202** [comment]
> Stand alone functions should (maybe?) pass _G as their first parameter

In strict mode (which is always enabled in ESM, so should be assumed everywhere in context of this transpiler) functions called without context don't have it at all, so it should be `nil`.

```js
function notStrict() { console.log(this) }
function strict() { 'use strict'; console.log(this) }
notStrict(); // => global context
strict(); // => undefined
```

I have implemented similar transformation: https://github.com/ark120202/babel-lua/tree/master/packages/babel-plugin-lua-function-context/__tests__/fixtures

It works fine, but some more issues to solve:

- External APIs global functions should be called without global context (`nil`), so that decorator that makes methods from external sources called with dot should support global functions. Or maybe just always call all global functions from external declarations without context.
- To use these functions as callbacks in external APIs they shouldn't have first argument. To do this I have used `__export()` macro. Alternatively it may be declared in user's function type, with something like a decorator but for types (function arguments, returns, objects). So

```typescript
x.asyncMethod(function(result) { console.log(result) });
x.asyncMethod(result => console.log(result));
x.asyncMethod(__export(function(result) { console.log(result) }));
const callback = result => console.log(result);
x.asyncMethod(callback);
```

should transpile to

```lua
x:asyncMethod(function(this, result) console:log(result) end
x:asyncMethod(function(_, result) console:log(result) end
x:asyncMethod(function(result) console:log(result) end
local callback = function(_, result) console:log(result) end
x:asyncMethod(___TS_ExportFunction(callback))

-- lib
function ___TS_ExportFunction(func)
	return function(...)
		return func(nil, ...)
	end
end
```

**Comment by tomblind** [comment]
> In strict mode (which is always enabled in ESM, so should be assumed everywhere in context of this transpiler) functions called without context don't have it at all, so it should be nil.

Forgot about strict mode! But TS does allow targeting older ES versions so perhaps it should use _G or nil based on ES target and use of strict.

> - External APIs global functions should be called without global context
> - To use these functions as callbacks in external APIs they shouldn't have first argument.

The way it's working in the branch right now, both of these are covered by the decorator. Decorated global functions won't be passed an initial context and functions transpiled by tstl with the decorator won't have an initial context parameter.

**Comment by tomblind** [comment]
So one thing that is proving annoying with this is updating external declarations with the new decorator. Having to put it on every function in a module is tedious and error prone. I think there's a strong case for a module-wide version that causes all non-methods in the file to be treated as if the were marked with the decorator.

**Comment by Perryvw** [comment]
Could an argument be made for having it by default true for methods, and false for functions, having both a positive and negative decorator?

**Comment by tomblind** [comment]
The problem with that is things get sticky when passing functions around:
```ts
function foo(fn: (s: string) => string) {
    return fn("foo");
}

function bar(s: string) {
    return s + "bar";
}

/** !NoContext */
function baz(s: string) {
    return s + "baz";
}

foo(bar);
foo(baz);
```
```lua
function foo(self,fn)
    return fn(nil,"foo")
end
function bar(self,s)
    return s .. "bar"
end
function baz(s)
    return s .. "baz" --attempt to concatenate local 's' (a nil value)
end
foo(nil,bar);
foo(nil,baz);
```

#192 is another example of where this would go wrong. Of course, this will still be a problem for functions with the decorator, but it seems less likely they'll be passed around like this. I wonder if it would be possible to detect decorated functions being assigned and wrap the call?

Right now I'm thinking something like this would be good for file-level:
```ts
/** !ModuleContext [all|methods|none] */
```
Where 'all' means all functions have a context parameter, 'methods' means only class methods do, and 'none' means no functions do (for libs that use closure-based classes). The default would be 'all'.

And then the following for individual functions (would override any file-level setting):
```ts
/** !Context [yes|no] */
```
Which defaults to 'yes'.

**Comment by tomblind** [comment]
The problem with that is things get sticky when passing functions around:
```ts
class Bar {
    public method(s: string): string {
        return s + "bar";
    }
}

function baz(s: string) {
    return s + "baz";
}

function foo(fn: (s: string) => string) {
    return fn("foo");
}

let bar = new Bar();
foo(bar.method);
foo(baz);
```
```lua
Bar = Bar or {}
Bar.__index = Bar
function Bar.new(construct, ...)
    local self = setmetatable({}, Bar)
    if construct and Bar.constructor then Bar.constructor(self, ...) end
    return self
end
function Bar.constructor(self)
end
function Bar.method(self,s)
    return s .. "bar"
end
function baz(s)
    return s .. "baz" --attempt to concatenate local 's' (a nil value)
end
function foo(self,fn)
    return fn(nil,"foo")
end
local bar = Bar.new(true);
foo(nil,bar.method);
foo(nil,baz);
```

#192 is another example of where this would go wrong. Of course, this will still be a problem for functions with the decorator, but it seems less likely they'll be passed around like this. I wonder if it would be possible to detect decorated functions being assigned and wrap the call?

Right now I'm thinking something like this would be good for file-level:
```ts
/** !ModuleContext [all|methods|none] */
```
Where 'all' means all functions have a context parameter, 'methods' means only class methods do, and 'none' means no functions do (for libs that use closure-based classes). The default would be 'all'.

And then the following for individual functions (would override any file-level setting):
```ts
/** !Context [yes|no] */
```
Which defaults to 'yes'.

**Comment by Perryvw** [comment]
Another thing to consider, if we have a declaration with a callback, how is that handled? Something like 
```ts
declare function ListenToGameEvent(eventName: string, callback: (event: GameEvent) => void);

ListenToGameEvent("someEvent", myFunction);

function myFunction(event:GameEvent) => void {
     print("Hello")
}
```
And what about replacing myFunction with a method inside a class?

**Comment by tomblind** [comment]
In this situation you'd need to specify "!Context no" on myFunction so it's transpiled without the extra parameter.

But if it's a class method, it would have to be wrapped in another function to preserve self anyways, right?

I've been playing around with some code that detects assignments of functions between types with/without context and wraps them accordingly in the output lua. It's a bit tricky, but if it works, it could prevent the need for users to have to manually address issues like this with callbacks.

**Comment by Perryvw** [comment]
Yeah I think having as much automatic detection is probably best. Although I would prefer a simple and clear system, I don't think we should go there at the cost of having extremely complex declarations, since the declarations are (in my opinion) the main selling point for this project. I would like to experiment with this a bit as well but I'm in the middle of moving so I still won't have time for a while.

Maybe I should look at a way to emulate externally declared lua in our test cases 🤔. Might be nice to have some tests for that.

**Comment by tomblind** [comment]
Yeah - while I usually dislike "magic" I'm definitely in agreement that interacting with external lua is paramount. It's not like lua is really ever used completely independently without external libs or an embedded api.

**Comment by tomblind** [comment]
Poking around at this more, I'm pretty confident the compiler can detect when no-context to with-context assignments are made (or vice versa). But magically wrapping the function is actually a bad idea.
Imagine an event system:
```ts
function subscribe(cb: () => void): void;
function unsubscribe(cb: () => void): void;
/** Context no **/
function foo() {}
subscribe(foo);
unsubscribe(foo);
```
Transpiled with "magic" conversions would be:
```lua
function foo() end
subscribe(nil, function(_, ...) foo(...) end) --foo gets wrapped to strip the context parameter
unsubscribe(nil, function(_, ...) foo(...) end) --Not the same instance of the function passed to subscribe!
```

I actually think the best thing to do would be to generate an error when doing a mis-matched assignment and let the user explicitly bind/wrap.
```ts
declare function foo(fn: () => void);
/** !Context no */
function bar() {}
foo(bar); //Error: cannot assign function without context to function type with context
foo(() => bar()); //All good
```

**Comment by Perryvw** [comment]
Did some thinking on this. The best solution I could some up with is to make a clear distinction: Methods are transpiled with a context and can use `this`. Everything else, like (arrow/anonymous) functions do not receive a context and should not use `this`.

The only place where this starts to act up is when passing a method to a function without context. In this case parameters will be missmatched. I am however confident we can detect this case, and if it occurs handle it by wrapping in an anonymous function.

I put some examples of proposed translations here: https://gist.github.com/Perryvw/27b6b9d2496e3920fbd2e205282a1e48

Please let me know your thoughts on this. One point of contention we discovered was how to deal with:
```ts
declare function ListenToGameEvent(eventName: string, handler: (event: string) => void): void;
ListenToGameEvent("abc", inst.myMethod);
```
Since `inst.myMethod` is a method (with context) and the parameter is not (no context), a wrapper is needed to ensure arguments are correct. My proposed solution is `function(event) return inst:myMethod(event) end` which means the method will keep its `inst` context. If you were to implement this in classical javascript or even c++, `this` inside `myMethod` would lose its value and be the scope in which ListenToGameEvent is called, something like `function(event) return inst.myMethod(currentScope, event) end`.

I persionally prefer keeping context as that seems logical to me (since it specifically asks for `myMethod` of `inst`) and is probably easier to implement, but @lolleko championed to how regular TypeScript handles this case. I am looking for some more opinions on this.

**Comment by tomblind** [comment]
I like this philosophically, but there's a lot of cases to consider:

Aside from passing a method as a callback, there's also re-assigning methods (such as #192).

Are lambda properties considered methods? Seems like they shouldn't be, but then there's the problem of interfaces obfuscating that fact:
```ts
declare class Foo {
    lambdaProp: (s: string) => string;
}

interface Bar {
    lambdaProp(s: string): string;
}

let bar: Bar = new Foo();

declare function ListenToGameEvent(eventName: string, handler: (event: string) => void): void;
ListenToGameEvent("abc", bar.lambdaProp); // lambdaProp will look like a method here, but it's not
```

And with the wrapping, as I mentioned before, there's cases that will silently break because the external code expects to get the same function reference in different calls (such as de-registering events).

Oh, and external code that uses closure-based objects and thus doesn't pass a context parameter will be difficult to declare.

It's a pretty tough issue and I have to admit I've been spinning in circles a bit on what the 'right' solution is. I'll keep thinking on it as well though.

**Comment by Perryvw** [comment]
For the wrapping issue, we could potentially make a `__noContextMyMethod = (args) => this.myMethod(args)` somewhere and then use that everywhere we need this wrapper. That would work but again will be a bit more complicated. Alternatively we could just throw an error on this case and force the user to explicitly do the lambda wrapping themself. I feel like that does not actually make it any more obvious however, now you have an exception that only shows up on compilation.

**Comment by tomblind** [comment]
That's a good idea, but it will need to be globally available everywhere the original function is.

In general, I've come to the opinion that magic function conversions is a bad idea as there will always be edge cases to deal with in non-standard code. It might be best to let the user determine the best course of action instead of trying to silently fix it for them. There are already other things that throw compiler errors such as bitwise ops. Actually, I was thinking it might be nice to build a set of tslint rules to cover special tstl situations so these the issues could be caught easily at edit-time.

Regarding the issue I mentioned with lambdas, I realized that this could be handled by giving lambda-properties a dummy first parameter so they could be called the same as methods. We would just need to handle them being assigned around the same as methods (wrap or error).

By the way, something I've been thinking about is that typescript actually has a mechanism for explicitly declaring the type of a functions context:
```ts
declare function bar(this: Foo): string;
```
This is stripped when generating js; it's just a type hint (this is actually a bug in tstl right now, as it doesn't get stripped there).

This could be used instead of decorators to explicitly declare a function as having or not having a context. In the later case, a method could be declared as "this: null". This would be easy to track in the compiler since it's part of the declaration and I think is clear what it does to the user. Thoughts?

**Comment by Perryvw** [comment]
Okay so in that case we should stick to methods and functions similar to how they are done currently. Methods will receive a context parameter, (so will any function using a `this` parameter.?). Anything else will not get any context parameter.

The cases where there might be issues we can throw TranspileErrors for now, and investigate if we define some tslint rules that can check this stuff while editing.

**Comment by tomblind** [comment]
Yes, I think that may be the best way to go. Even if we throw errors now, that leaves the option open to do a smarter conversion later.

I've gone through a put together a code run-down to make sure this makes sense.

Methods and lambda properties:
```ts
class Foo {
    method(s: string) { return s; }
    lambdaProp: (s: string) => string = (s) => s;
    static staticMethod(s: string) { return s; }
    static staticLambdaProp: (s: string) => string = (s) => s;
}
```
=>
```lua
function Foo.new(construct, ...)
    ...
    self.lambdaProp = function(_, s) return s end --Note the dummy parameter
    ...
end

function Foo.method(self,s)
    return s
end

function Foo.staticMethod(s)
    return s
end

Foo.staticLambdaProp = function(s) return s end
```
Note here that static methods would NOT get a self parameter anymore (as they do right now), in order to keep things consistent.

```ts
// Note this interface swaps the method and lambda signatures
interface I {
    method: (s: string) => string;
    lambdaProp(s: string): string;
}

let foo: I = new Foo();

let a = foo.method("a");
let b = foo.lambdaProp("b");

let c = Foo.staticMethod("c");
let d = Foo.staticLambdaProp("d");
```
=>
```lua
local foo = Foo.new();

--Lambda properties and methods are called the same way
local a = foo:upper("a");
local b = foo:lower("b");

local c = Foo.staticMethod("c");
local d = Foo.staticLambdaProp("d");
```

Stand-alone functions and lambdas:
```ts
function func(s: string): string { return s; }
const lambda = (s: string) => s;
let e = func("e");
let f = lambda("f");
```
=>
```lua
function func(s) return s end
local lambda = function(s) return s end  --Note there is NO dummy parameter
local e = func("e");
local f = lambda("f")
```

Assigning functions to methods:
```ts
// ERROR: Cannot assign function to method
foo.method = func;

// Workaround
function wrapFunc(this: Foo, s: string) { return func(s); }
foo.method = wrapFunc;
```
=>
```lua
function wrapFunc(self, s) return func(s) end
foo.method = func
```

Special case: we don't need to require explicit 'this' when assigning directly to function expression.
```ts
foo.method = (s) => s;
foo.lambdaProp = function(s) { return s; }
```
=>
```lua
foo.method = function(_, s) return s end
foo.lambdaProp = function(self, s) return s end
```

Assigning methods to functions:
```ts
interface Func { (s: string): string; }
function takesFunc(f: Func) {}

// ERROR: Cannot assign method to function
let fn1: Func = foo.method;

// Workaround
let fn2: Func = (s) => foo.method(s);

// ERROR: Cannot assign method to function
takesFunc(foo.method);

// Workaround
takesFunc((s) => foo.method(s));
```
=>
```lua
local fn2 = function(s) return foo:method(s) end

takesFunc(function(s) return foo:method(s) end)
```

Closure-based classes:
```ts
declare class Bar {
    method(this: null, s: string): string;
}
let bar = new Bar();
let g = bar.method("g"); // The 'this' context of type 'Bar' is not assignable to method's 'this' of type 'null'.
```
This doesn't actually work as I had hoped because typing 'this' as null prevents the method from being callable. We could use something else like "{}" or "unknown" (TS3+). Or we could stick with a "!NoContext" decorator for this situation.

**Comment by tomblind** [comment]
It turns out that last example works if 'this' is typed as void:
```ts
declare class Bar {
    method(this: void, s: string): string;
}
let bar = new Bar();
let g = bar.method("g"); //Ok
```
This seems like the most 'correct' way to do this.
