### ISSUE TITLE
Using Lua's length operator "#"

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#261]
Right now we are using `#` to translate `Array.length`.
However Lua's `#` behaves slightly different if a array containts "gaps"

```lua
local x = {1,2}
x[5] = 12
print(#x) -- prints 2 (executed in https://www.lua.org/cgi-bin/demo)
```
```ts
var arr = [1, 2];
arr[5] = 12;
console.log(arr.length); -- logs 6
```

Right now `length` is the only place where we use `#`,
but we were thinking about using `#` in forOf translation aswell #260.

Here are some possible solutions to the problem:

- Leave it to the programmer not to have gaps in arrays and use `#` in transpiled lua.

- Add a custom array type to lualib that patches `__index` and `__newindex` to keep track of the array/table length. (Probably wont work if arrays are passed from native lua)

- Add an transpiler options called "safe mode" where we replace `#` with a custom function that gets the length by iterating with pairs. In unsafe mode just keep using `#`.

**Comment by tomblind** [comment]
The problem with trying to emulate javascript's behavior is that there's no way currently to deal with null.
```ts
let a: (string | null)[] = ["foo", null];
print(a.length); // 2 in JS, 1 in lua
```

I think this might fall into the same category as falsey values (#231) where the rules of lua are kept (and documented).

**Comment by lolleko** [comment]
I think this is different than #231. Truthy/falsey values are a really bad feature we dont have to support, because most people avoid those anyway. But having arrays with gaps is more common, can be useful and are something that you expect to work without thinking about it.

I dont know how valuable the length property for arrays with gaps is, but you defintly want to be able to  iterate those arrays and that wont work rn.

**Comment by tomblind** [comment]
I can see your point about sparse arrays being actually useful. But the pairs solution won't work on arrays with trailing nulls. A full replacement would be the only way to get accurate behavior. That's kind of a lot of overhead for something as extremely common as arrays, so I would hope it would be optional one way or another.

**Comment by lolleko** [comment]
Im fine with treating the default the same as #231. But I think we should really make a compilerOption that enables the use of our own "safe arrays", similar to what @Perryvw mentioned above.

Moved to #262 and #263
