### ISSUE TITLE
Use JSDoc tags instead of decorators 

### ISSUE THREAD

**Issue by ark120202** [Perryvw/TypescriptToLua#267]
Reasoning:

1. Naming them "decorators" causes confusion with [ES Decorators Proposal](https://github.com/tc39/proposal-decorators) (which may reach stage 3 soon enough).

2. Custom JSDoc tags are already used in TypeScript - `/** @internal */`, so it looks like the most obvious way to define custom behavior for types.

3. Custom JSDoc tags may be supported by editors and documentation generators, custom syntax never would be.

<details>

Decorator:

![Decorators](https://user-images.githubusercontent.com/11750369/47401768-15f2d900-d75c-11e8-83af-be1bfe1c089a.png)

JSDoc Tag:

![JSDoc Tags](https://user-images.githubusercontent.com/11750369/47401772-18553300-d75c-11e8-817b-e7a8d9e2444d.png)

</details>

**Comment by Perryvw** [comment]
Done with ce74fe629fbd8329680e645db48eb860ec020f31
