### ISSUE TITLE
Creating custom libraries

### ISSUE THREAD

**Issue by ark120202** [Perryvw/TypescriptToLua#270]
One of the best features of JS/TS ecosystem is the ability to create and reuse code with npm packages.
Currently it's impossible to create consumable libraries for Lua.
While working on my transpiler I have investigated it, so that's what I came up with:

## Variant 1 - Transpilation done by application developer

* Enforces some strict project structure for library authors
* Requires reimpementing some TypeScript's project organization features, like project references
* Makes transpiler API less flexible, since new TS programs would be created for each library internally
* Would make transpilation a lot slower, unless some caching would be added

## Variant 2 - Transpilation done by library developer

* TypeScript and Babel are doing this
* Allows to create projects that compile to both Lua and JS
* Allows library author to use different/patched version of tstl and use custom plugins
* Allows library author to customize build phase as they want (cli, gulp, custom scripts)
* Allows to use libraries written manually with Lua and .d.ts files
* Requires development of standard library as a separate package (maybe in a monorepo), so multiple libraries would use only one instance and version conflicts would be avoided with semver. TS is doing the same thing with tslib.
* Complicates import path resolving process (but also makes it more flexible)
* Not allows to configure optimizations globablly. For example if #262 would be done as an option it won't be possible to use multiple libraries that are using different configurations
* Libraries would be distributed like in TS - with a .lua and .d.ts files. To generate declarations `tsc --emitDeclarationOnly` could be used, but...
* Some of semantics is lost on compilation phase. For example

```typescript
export class A {
  get foo() {
    return 1;
  }
}
```

```typescript
export declare class A {
    readonly foo: number;
}
```

So that would require customizing declaration generation to insert some metadata, similarity to what Kotlin is doing with generated java class files.

```typescript
/** @TypeScriptToLuaMetadata {getters:["A.foo"]} */

export declare class A {
    readonly foo: number;
}
```

---

I personally prefer second variant, but it comes with more issues to solve.

**Comment by Perryvw** [comment]
I think it is possible to have a nice intermediate step here. I think if we allow other projects to extend and override our transpiler classes that would already add some nice extensibility. Additionally we should probably add a function to the public api that accepts a typescript AST instead of a string/file so people can  decide where they get their AST from and what else to do with it.

**Comment by ark120202** [comment]
> Additionally we should probably add a function to the public api that accepts a typescript AST instead of a string/file so people can decide where they get their AST from and what else to do with it.

That's actually how I'm planning to integrate it to my project. Won't already exported `LuaTranspiler*` classes be enough for that or am I missing something?

> I think if we allow other projects to extend and override our transpiler classes that would already add some nice extensibility

Sorry, I don't quite understand how it's related to this topic. Do you mean that npm modules may be compiled with some extended transpiler to avoid enforcing some strict practice on this?

**Comment by Perryvw** [comment]
For the first point I mean we should have a `transpileAST` besides our `transpileString` and `transpileFile`, so that people choose how they get their typescript AST them self.

Second point I am indeed thinking of people that require specific transpiler functionality sould simply create their own transpiler class, extending for example our `LuaTranspilerJIT` like you mentioned, or did I missunderstand?

**Comment by ark120202** [comment]
It's not something specific to my environement. Any Lua project may be able to use modules, just like importing regular files. The resulted code would have only simple Lua's requrie calls. What I want (for example with first variant since it's simpler) is that running `tstl` would generate a completely working project (unless there is something environment specific and considering that all code is valid). So one of it's steps should find all imported modules, look for them in `node_modules`, find their TS configs and run the same transpilation code on each module. So the generated lua directory would contain a `node_modules` directory that would contain already transpiled modules.

Actually, in my case it might be easier to implement it in my project first, since I would have to use API directly anyway.
But later it might be useful to move some of stuff I'll come up with to the core (and support it in API and CLI), so users of different environments won't have to write different transpilers for different environemnts even if there's no need to do adjustments to actual tranpilation phase. Also it would allow to make a unified standard for writing Lua modules (for example some specific key in `package.json` that defines all projects that should be handled by tstl)

Feel free to close this issue for now, since it's resolved in my specific case.
