### ISSUE TITLE
Post-incrementing properties generates invalid identifiers

### ISSUE THREAD

**Issue by velcroz** [Perryvw/TypescriptToLua#276]
Post-incrementing properties or array values generates invalid lua identifiers
```typescript
class Test {
	lastId = 0;

	constructor() {
		log(this.lastId++);
	}
}
```
The generated code looks like this
```lua
log((function()
        local __originalValueself.lastId0 = self.lastId;
        self.lastId = (self.lastId+1);
        return __originalValueself.lastId0;
 end
```
A similar situation happens when trying to access a variable using bracket notation
```typescript
let data = {value : 0};
log(data['value']++);
```
Generated code:
```lua
local data = {value = 0};
log((function()
    local __originalValuedata["value"]0 = data["value"];
    data["value"] = (data["value"]+1);
    return __originalValuedata["value"]0
end
)());
```

**Comment by tomblind** [comment]
I believe this is the same as #221 which is fixed by #241.

**Comment by Perryvw** [comment]
In that case please make sure you are on v0.11.0. If you are still having this issue let us know!

**Comment by velcroz** [comment]
You're right, the issue disappeared after upgrading to the newest version
