### ISSUE TITLE
Add custom iterator support

### ISSUE THREAD

**Issue by Perryvw** [Perryvw/TypescriptToLua#277]
We should add support for [non-standard iterators](https://basarat.gitbooks.io/typescript/docs/iterators.html), probably by implementing an iterator class in the LuaLib.

**Comment by tomblind** [comment]
Somewhat related: I'd love to be able to use lua-style iterators (such as string.gmatch) in for...of loops.
```ts
declare namespace string {
    export function gmatch(s: string, pat: string): Iterable<string[]>;
}

for (let [c] of string.gmatch("foo", ".")) {
    print(c);
}
```

Right now the call to gmatch is wrapped in pairs(). Perhaps a custom decorator could be used?

**Comment by Perryvw** [comment]
Added in c880ef621ab5e60d8023677b0cf694a22cad79e8
