### ISSUE TITLE
'this' parameter not stripped from function declarations

### ISSUE THREAD

**Issue by tomblind** [Perryvw/TypescriptToLua#281]
TS allows you to explicitly type 'this' in function declarations, but it's just a typing hint that should be stripped on compilation. Currently, it is still added to the output declaration:
```ts
class Foo {
    public method(this: Foo, s: string): string { return "foo" + s; }
}
```
=>
```lua
Foo = Foo or {}
Foo.__index = Foo
function Foo.new(construct, ...)
    local self = setmetatable({}, Foo)
    if construct and Foo.constructor then Foo.constructor(self, ...) end
    return self
end
function Foo.constructor(self)
end
function Foo.method(self,this,s) --this is going to be a problem
    return "foo" .. s
end
```

**Comment by Perryvw** [comment]
Should we take this to mean we should bind self explicitly by defining the method inside `new` so it bakes in the value of `self`? (replace the self parameter with a dummy)

**Comment by Perryvw** [comment]
Actually the most straightforward way to implement is to just ignore `this` for methods, and interpret it as adding a `self` argument to any function using it. This would require some extra checks when transpiling function calls.
