### ISSUE TITLE
Implementing a LuaLib in Lua

### ISSUE THREAD

**Issue by hazzard993** [Perryvw/TypescriptToLua#290]
I'm working on #252, my current solution uses some extra Lua code wrapped up in a LuaLib titled `__TS__TryCatchFinally`, it works for all supported Lua environments and makes try/catch/finally work just how it would in NodeJS/JavaScript.

I don't know where to put it through and think it might be an advantage for contributors if they could write pure Lua LuaLib libraries.

For an idea of how they would do this, they would place these as `.lua` files within `src/lualib` and these files would be moved to `dist/lualib` along with the other LuaLib files. Then they would reference the name of the LuaLib file within `LuaLibFeature` to put it to use in the Transpiler.

It feels a bit hacky to re-write my Lua code in TypeScript since, for this instance, the code relies exactly on how Lua's error handling works and Lua specific functions.

Is this something ideal to add?

**Comment by Perryvw** [comment]
Closing this for now as this is not something currently on our radar, unless it turns out this is required.
