### ISSUE TITLE
Multiple returns 

### ISSUE THREAD

**Issue by Istar-Eldritch** [Perryvw/TypescriptToLua#293]
Lua supports multiple returns (https://www.lua.org/pil/5.1.html). When writing modules that will interoperate with lua code sometimes is necessary to access the second returned value.

I understand this is a limitation of the typescript syntax and there is not much we can do about it unless we get creative. A common pattern in javascript to achieve the same functional behavior thing is destructuring an array.

I've seen that `tstl` currently does an `unpack` when it finds the destructuring syntax. I'm not sure if its possible, but could we generate extra code to first identify if the function is doing multiple returns, and if so, fill the destructured variables with the results instead of doing unpack?

**Comment by lolleko** [comment]
Does https://github.com/Perryvw/TypescriptToLua/wiki/Custom-Decorators#tuplereturn not work for you?

**Comment by Istar-Eldritch** [comment]
Oh my, yes that works. :smile:
Sorry, I didn't check that section of the wiki.

Closing.
