### ISSUE TITLE
Static methods have no self parameter

### ISSUE THREAD

**Issue by hazzard993** [Perryvw/TypescriptToLua#320]
Found a bug, looks like transpiled static methods no longer have a `self` parameter.

```ts
class Player {
    static initialize() {
        this.x = 0;     // this = Player
    }
}

Player.initialize();
console.log(Player.x);
```

When transpiled to Lua `initialize` turns into

```lua
function Player.initialize()
    self.x = 0;
end
```

So that function won't work, `self` will always be `nil`.

Transpile and run this code with `tsc` and `node` and you'll get an output of `0`.

`tsc main.ts && node main.js`

**Comment by lolleko** [comment]
So static methods should always have a self parameter and the class itself (Player) should always be passed as first argument in these cases.

eg.
```lua
function Player.initialize(self, y)
    self.x = 0;
    self.y = y;
end

Player.initialize(Player, 123)
```

while we fix this you can use:

```ts
class Player {
    static initialize() {
        Player.x = 0;     // this = Player
    }
}

Player.initialize();
console.log(Player.x);
```

to work around this.

**Comment by tomblind** [comment]
We changed this with the new function stuff. It makes sense to revert static methods back to being "method-like" (taking a self parameter), but this means that declarations for classes in lua libs that have static methods will likely need to be declared like this:
```ts
declare class Foo {
    static bar(this: void): void;
}
```
Or they will incorrectly be passed an additional parameter.

Alternatively, we could make using 'this' in static methods an error. I like this option less, but I think it comes down to what is the more common scenario: static methods written in TS using 'this' or lua lib classes having static methods?

**Comment by tomblind** [comment]
I've definitely seen plenty of lua libs use static-like methods (usually wrappers around c++ apis like wxLua). But thinking about it, it seems best to put the burden on the declaration writers rather than the regular users, so treating statics as methods is probably the best way to go.

**Comment by lolleko** [comment]
Instead of passing self as param we could just declare it at the start of the function body:
```lua
function Player.initialize(y)
    local self = Player
    self.x = 0;
    self.y = y;
end

Player.initialize(123)
```

This would leave declarations untouched because we don't transpile them, but work for classes that are actually transpiled.

**Comment by tomblind** [comment]
That's a pretty cool idea. But, it would break if the method is re-assigned:
```ts
class Foo {
    static prop = "bar";
    static staticMethod() {
        return "foo" + this.prop;
    }
}
function bar() {
    return "bar" + this.prop;
}
Foo.staticMethod = bar;
```
