### ISSUE TITLE
Improve Readme and documentation

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#33]
Documentation on the custom decorators would be nice.

**Comment by zapp-brannigan-dota** [comment]
[Limitations](https://github.com/Perryvw/TypescriptToLua/wiki/Limitations) string functions section can be updated with:

- string.charAt()
- string.split()
- string.toLowerCase()
- string.toUpperCase()

**Comment by Perryvw** [comment]
Done @zapp-brannigan-dota

**Comment by Perryvw** [comment]
TODO:
- [ ] Write a page on project setup
- [ ] Add `!TupleReturn` to decorators page
- [ ] Improve decorator page examples.

**Comment by lolleko** [comment]
> Write a page on project setup

The idea is that our cli works exactly like the typescript cli. So we should probably just link to https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by lolleko** [comment]
Added some info about project setup to: 
https://github.com/Perryvw/TypescriptToLua/wiki

Closing this issue, future documentation requests should be made in their own issues.
