### ISSUE TITLE
Playground unusable on iOS

### ISSUE THREAD

**Issue by MartyMaro** [Perryvw/TypescriptToLua#339]
i’m leaning typescript on my mobile right now and noticed some problems when i triefd to see what Lua I get by using your playground on Chrome.  

I cannot select all code, your custom menu just opens and there is no way to select all nor to paste. also it always zooms in, so the text gets very huge.

**Comment by lolleko** [comment]
Hey we are using Visual Studio Code's Monaco Editor (https://github.com/Microsoft/monaco-editor) for the Playground. This Editor curretnly has no Touchscreen/Mobile support.

We dont have any plans to add support ourself or switch editors at this time.
So I'm afraid you will have to use the Playgropund on a Desktop/Laptop.
