### ISSUE TITLE
the lua5.3 interpreter does not define "unpack"

### ISSUE THREAD

**Issue by tjahn** [Perryvw/TypescriptToLua#386]
Hello,

src/lualib/FunctionCall.ts
src/lualib/FunctionBind.ts
src/lualib/FunctionApply.ts

all rely on the lua "unpack" function. 
For me it is working fine in lua5.1 but lua5.3 does only define "table.unpack" instead.

Something like
`unpack = unpack or table.unpack`
at the beginning of the lualib_bundle could solve this issue.

Best regards, tjahn

**Comment by Perryvw** [comment]
LuaLib is built on distribution time at the moment. This presents a real problem when transpiling to different Lua targets. We will probably have to end up transpiling the lualib on project compilation.

**Comment by tomblind** [comment]
It looks like all three of those lib functions already mitigate unpack in the way you suggested:
```lua
__TS__FunctionCall = function(fn, thisArg, ...)
    local args = ({...});
    return fn(thisArg, (unpack or table.unpack)(args));
end;
```
Are you sure you are using the latest version?

**Comment by tjahn** [comment]
Oh yes, I am sorry. I apparently did not investigate close enough. 
The problem I experienced actually did not arise in these three files. 
However, this here:

`
function func1( ...args: any[] ){ }
function func2( ...args: any[] ){ 
    return func1( ...args ); 
}
`
compiles to that: 
`
local func1;
func1 = function(...)
    local args = ({...});
end;
local func2;
func2 = function(...)
    local args = ({...});
    return func1(unpack(args));
end;
`

**Comment by tomblind** [comment]
Hmmmm... strange. If I compile that code with --luaTarget 5.3 I get this:
```lua
local func1;
func1 = function(...)
    local args = ({...});
end;
local func2;
func2 = function(...)
    local args = ({...});
    return func1(table.unpack(args));
end;
```
What are your command-line options/tsconfig?

**Comment by tjahn** [comment]
Oh no, I am really sorry for the inconvenience.
I selected the wrong tsconfig.json and kept building it for the default target. Should have used the command-line argument to be sure.
Many thanks for your efforts

**Comment by tomblind** [comment]
No problem - it happens!
