### ISSUE TITLE
Destructuring assignment

### ISSUE THREAD

**Issue by Trildar** [Perryvw/TypescriptToLua#4]
Relevant pages:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
https://www.typescriptlang.org/docs/handbook/variable-declarations.html

This can be supported by creating temporary variables and then doing assignment from those variables, much like how the regular TypeScript compiler does it.
e.g. `let [a, b] = [1, 2]` could translate to `local _a = {1, 2}; local a = _a[1]; local b = _a[2]` or separate the declaration of the variables to another line if possible, to avoid having `local` a bunch of times.

`let [a, b] = [1, 2]` could also technically translate to `local a, b = 1, 2`, but I'm not sure trying to recognise when multiple assignment can be used would be worth it.

Supporting `...rest` would probably need some helper function, since Lua doesn't have an equivalent to JavaScript's `Array.prototype.slice`.

**Comment by Perryvw** [comment]
Added list.slice() and destructing list types with commit b57d82462a04cc5f6cefb35136fab2f0e34bf054. For now destructing object types will not be supported.
