### ISSUE TITLE
Support install from github

### ISSUE THREAD

**Issue by tjahn** [Perryvw/TypescriptToLua#420]
Hello,

I would like to install tstl directly from github like this:
> npm install github.com/Perryvw/TypescriptToLua#master
This however is not supported, since the dist-directory is not present in the github.
The advantage would be that projects can be more comfortable and faster be updated to the newest tstl, even different branches or forks without having to manually checkout and build it.

What I propose is to add a preinstall and postinstall to the package.json and build tstl during the installation procedure of npm. Thus shipping it with the *.ts files instead of a prebuild dist-directory.
Since typescript already is an dependency of tstl it should easily be possible to directly use it for building tstl during the installation. That would also avoid contributors to use different typescript versions for building tstl. 

Are there any opinions to that?

**Comment by ark120202** [comment]
We can just configure ci to release package to npm with `@next` tag on each commit to master

**Comment by tjahn** [comment]
Yes, but I would still not be able to install from my fork etc

**Comment by ark120202** [comment]
- For building you also need `ts-node`
- If it's your fork why not just use npm link? Of course it's temporary solution, but I don't see any reason to use forked version constantly
- You can already do this with a postinstall script on user side
- That would make instantiation slower and would break for users that disabled running scripts on install
- postinstall scripts are meant to do environment-specific work, like downloading or building binaries. Using it for something like that just doesn't look right
- I have never seen other projects doing this

**Comment by Perryvw** [comment]
I don't think we will be doing this. GitHub is meant for tracking source files, not distributing packages (which is npm's job). You can pull the repository and then run `npm install -g .` in its directory to install the latest development version of tstl on your machine.

That being said, I will try to publish patch versions a little more often ;)

Closing this for now.
