### ISSUE TITLE
Support only standard jsdoc annotation casing

### ISSUE THREAD

**Issue by ark120202** [Perryvw/TypeScriptToLua#422]
It doesn't really add anything but inconsistency.
Would be a breaking change, so we should just show the warning now and stop supporting it with #365.

**Comment by Perryvw** [comment]
JsDoc itself is not case sensitive, as you can see here: https://github.com/jsdoc3/jsdoc/blob/master/test/specs/jsdoc/tag/dictionary.js#L125 . Therefore I think we should not force this but leave it up to the user to decide.
