### ISSUE TITLE
namespace or module exporting error

### ISSUE THREAD

**Issue by jishunfei** [Perryvw/TypeScriptToLua#434]
ts:
```ts
module test {
    export class bbbb {

    }
}
class cccc extends test.bbbb {

}
```

lua:
```lua
local test = test or {}
do
    local bbbb = bbbb or {}
    bbbb.__index = bbbb
    function bbbb.new(construct, ...)
        local self = setmetatable({}, bbbb)
        if construct and bbbb.constructor then bbbb.constructor(self, ...) end
        return self
    end
    function bbbb.constructor(self)
    end
    test.bbbb = bbbb
end
local cccc = cccc or bbbb.new()
cccc.__index = cccc
cccc.__base = bbbb
```

!!!!! bbbb.new() is error!  
===> test.bbbb.new()
Thanks!

**Comment by jishunfei** [comment]
Thanks!
this is ok:
module test {
    export class bbbb {
    }
}
class cccc extends test.bbbb {
}

but:
namespace test.AAAAA {
    export class bbbb {
        constructor(){}
    }
}
class cccc extends test.AAAAA.bbbb {
    constructor(){super();}
}
==> bbb is missing!!!
local test = test or {};
local cccc = cccc or {};
cccc.__index = cccc;
cccc.prototype = cccc.prototype or {};
cccc.prototype.__index = cccc.prototype;
cccc.prototype.constructor = cccc;
cccc.____super = test.AAAAA.bbbb;
setmetatable(cccc, cccc.____super);
setmetatable(cccc.prototype, cccc.____super.prototype);
cccc.new = function(...)
    local self = setmetatable({}, cccc.prototype);
    self:____constructor(...);
    return self;
end;
cccc.prototype.____constructor = function(self)
    cccc.____super.prototype.____constructor(self);
end;

**Comment by tomblind** [comment]
Just to clarify the bug here: namespaces with dot in their name don't export anything:
```ts
namespace a.b {
    export const foo = "foo";
}
```
=>
```lua
a = a or {}
```
These should be treated as nested namespaces and handled correctly.
