### ISSUE TITLE
static function error

### ISSUE THREAD

**Issue by jishunfei** [Perryvw/TypeScriptToLua#435]
Hi !
ts:
export class test{
    static testSfunc(){}
}
test.testSfunc();

but lua error:
exports.test:testSfunc();

===> exports.test.testSfunc();
I must write ts: 
static testSfunc(this: void){}

Thanks!

**Comment by hazzard993** [comment]
See #320

The `self` parameter is there because of this use case:

```ts
export class Player {
    public static x: number;
    static initialize() {
        this.x = 0;     // this = self = Player
    }
}

Player.initialize();
console.log(Player.x); // 0
```

`this: void` lets TypeScript know that there is no `this` in the method and lets the Transpiler know to not create a `self` parameter.

**Comment by jishunfei** [comment]
OK, I see! Thank you!
