### ISSUE TITLE
Improving documentation of javascript truthyness

### ISSUE THREAD

**Issue by TomSputz** [Perryvw/TypeScriptToLua#442]
The True/False values section of <https://github.com/Perryvw/TypeScriptToLua/wiki/Differences-between-Lua-and-Javascript> is a bit clunky - this makes it easier to understand the point.

| **Language**   	| false 	| undefined (`nil`) 	| null (`nil`) 	| NaN (`nil`) 	| "" 	| 0 	| Everything Else 	|
|----------------	|-------	|-------------------	|--------------	|-------------	|----	|---	|-----------------	|
| **Javascript** 	| ✗     	| ✗                 	| ✗            	| ✗           	| ✗  	| ✗ 	| ✔               	|
| **Lua**        	| ✗     	| ✗                 	| ✗            	| ✗           	| ✔  	| ✔ 	| ✔               	|

Could be ✓ for a subtler look

**Comment by endel** [comment]
Maybe something like this, but I feel this table is still a bit confusing. We're exposing two things at the same time here: what values are being converted from JS to LUA, and what these types are going to be evaluated as `true` or `false`

| JavaScript Values | `false` | `undefined`  | `null` | `NaN` | `""` | `0` | (Everything else) |
| --- | --- | --- | --- | --- | --- | --- | --- |
| JavaScript behaviour | `false` | `false` | `false` | `false` | `false` | `false` | `true` | 
| Lua behaviour | `false` | `nil` → `false` | `nil` → `false`  | `nil` → `false` | `true` | `true` | `true` |

**Comment by Perryvw** [comment]
Great suggestion, how about transposing and taking a little of both tables:

|TypeScript|_JavaScript behavior_|_Lua behavior_|
|---|---|---|
|`false`|`false`|`false`|
|`undefined`|`false`|`nil`→ `false`|
|`null`|`false`|`nil`→ `false`|
|`NaN`|`false`|`nil`→ `false`|
|`""`|⚠️`false`|⚠️`true`|
|`0`|⚠️`false`|⚠️`true`|
|(Everything else)|`false`|`false`|

**Comment by Perryvw** [comment]
Put the table on the wiki.
