### ISSUE TITLE
"Unsupported conversion from function to method"

### ISSUE THREAD

**Issue by endel** [Perryvw/TypeScriptToLua#444]
Hey there,

Any idea why this is not valid for transpilation? Cheers!

**Code**

```typescript
export class Raft {
    onBlockDestroyedCallback: (affectedBlocks: any[]) => void;
    onLinesUpdatedCallback: () => void;

    constructor (userData: any, boat: any) {
    }

    update () {
        if (this.onBlockDestroyedCallback) {
            this.onBlockDestroyedCallback([]);
        }
        if (this.onLinesUpdatedCallback) {
            this.onLinesUpdatedCallback();
        }
    }

    onBlockDestroyed (cb: (affectedBlocks: any[]) => void) {
        this.onBlockDestroyedCallback = cb; // here
    }

    onLinesUpdated (cb: () => void) {
        this.onLinesUpdatedCallback = cb; // here
    }

}
```

**Error**

```
Uncaught Error: Unsupported conversion from function to method. To fix, wrap the function in an arrow function or declare the function with an explicit 'this' parameter.
```

**Playgound link**

https://typescripttolua.github.io/play.html#src=%0Aexport%20class%20Raft%20%7B%0A%20%20%20%20onBlockDestroyedCallback%3A%20(affectedBlocks%3A%20any%5B%5D)%20%3D%3E%20void%3B%0A%20%20%20%20onLinesUpdatedCallback%3A%20()%20%3D%3E%20void%3B%0A%0A%20%20%20%20constructor%20(userData%3A%20any%2C%20boat%3A%20any)%20%7B%0A%20%20%20%20%7D%0A%0A%20%20%20%20update%20()%20%7B%0A%20%20%20%20%20%20%20%20if%20(this.onBlockDestroyedCallback)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.onBlockDestroyedCallback(%5B%5D)%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20if%20(this.onLinesUpdatedCallback)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.onLinesUpdatedCallback()%3B%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%0A%20%20%20%20onBlockDestroyed%20(cb%3A%20(affectedBlocks%3A%20any%5B%5D)%20%3D%3E%20void)%20%7B%0A%20%20%20%20%20%20%20%20this.onBlockDestroyedCallback%20%3D%20cb%3B%0A%20%20%20%20%7D%0A%0A%20%20%20%20onLinesUpdated%20(cb%3A%20()%20%3D%3E%20void)%20%7B%0A%20%20%20%20%20%20%20%20this.onLinesUpdatedCallback%20%3D%20cb%3B%0A%20%20%20%20%7D%0A%0A%7D%0A

**Comment by tomblind** [comment]
`onBlockDestroyedCallback` and `onLinesUpdatedCallback` are considered method-like (have a `self` parameter), but the `cb` parameter is not method-like. If this was allowed, the callback would be given a self parameter when it isn't expecting one.

If you intend `onBlockDestroyedCallback` and `onLinesUpdatedCallback` to take a `self` parameter, change `cb` like this:
```ts
onBlockDestroyed (cb: (this: Raft, affectedBlocks: any[]) => void) {
    this.onBlockDestroyedCallback = cb; // here
}
```
Or, if you they don't need a self parameter in those callbacks, change `onBlockDestroyedCallback` and `onLinesUpdatedCallback` like this:
```ts
onBlockDestroyedCallback: (this: void, affectedBlocks: any[]) => void;
onLinesUpdatedCallback: (this: void) => void
```

More info about this can be found in the wiki:
https://github.com/Perryvw/TypeScriptToLua/wiki/Differences-Between-Functions-and-Methods

**Comment by endel** [comment]
Wow, this is neat. Bad types from my end them, thanks a lot for your swift reply! ❤️
