### ISSUE TITLE
Variable declarations are always local

### ISSUE THREAD

**Issue by zapp-brannigan-dota** [Perryvw/TypescriptToLua#5]
I tried to include JSON data by having a config.ts with `let config = {};`, but that transpiles to `local config = {}`.
Then when you do `require('config');` nothing happens and config is undefined. I fixed this by removing the local part:
```
    LuaTranspiler.prototype.transpileVariableDeclaration = function (node) {
        // Find variable identifier
        var identifier = node.name;
        if (node.initializer) {
            var value = this.transpileExpression(node.initializer);
            return "" + identifier.escapedText + " = " + value;
        }
        else {
            return "" + identifier.escapedText + " = nil";
        }
    };
```

**Comment by zapp-brannigan-dota** [comment]
Apparently this is supposed to happen because `var` and `let` are locally scoped. So my question now is how to load json again. One thing that is important to me is to be able to use a json dump because I define the values in an actual json file somewhere.

**Comment by Perryvw** [comment]
To declare a global variable in TypeScript you have to explicitly declare them first. For example:
```
declare var myGlobalVar: any;
myGlobalVar = {a: 3, b: "hello"};
```
