### ISSUE TITLE
Experimental feature: Alias calls

### ISSUE THREAD

**Issue by Perryvw** [Perryvw/TypescriptToLua#56]
Related pull request: #55 

You can define a type alias as follows:
```typescript
type C_DOTA_BaseNPC = CDOTA_BaseNPC;
``` 
Then an explicit cast would cause the transpiler to use the alias instead of the original class. For example
```typescript
unit.GetMana()                      ==>   CDOTA_BaseNPC.GetMana(unit)
(<C_DOTA_BaseNpc>unit).GetMana()    ==>   C_DOTA_BaseNPC.GetMana(unit)
```

From now on this experimental feature will be merged into the main branch to test. Please report any issues with this mechanic here.

This feature will remain open until this experimental feature is reverted or added permanently.

**Comment by zapp-brannigan-dota** [comment]
The type aliases pollute the code completion and should probably be kept in a separate file so they can be excluded.

**Comment by Perryvw** [comment]
You should be able to simply put them in your declarations file.

**Comment by zapp-brannigan-dota** [comment]
For Dota they are in the general declarations file and that causes them to pop up in code completion which is annoying. If they were in a separate file people could choose to exclude them from their code completion.

**Comment by Perryvw** [comment]
Removed the need for this in 17378efff93ed72bfb7ed01016c0aeb17d5092c3
