### ISSUE TITLE
Add identifier aliases

### ISSUE THREAD

**Issue by aemino** [Perryvw/TypescriptToLua#65]
This is somewhat related to #56.  It would be useful to be able to re-name various identifiers such as class names, method names, etc. in definition files.  Perhaps this could be done using either a native TypeScript feature or via custom decorators.

**Comment by Perryvw** [comment]
Could you give an example?

**Comment by aemino** [comment]
Say I have an interface:
```ts
interface SomeLuaClass {
  /** !Native SomeLuaMethod */
  someLuaMethod(a: int, b: int): float;
}```
Essentially this is declaring `someLuaMethod` on the TS side, but the custom decorator would signal to the transpiler that the actual method name is `SomeLuaMethod`.

**Comment by Perryvw** [comment]
Why go through all the effort of renaming instead of just declaring it as SomeLuaMethod?

**Comment by aemino** [comment]
I think that many people would agree that having consistency in naming schemes across a programming language is a good idea.  It's nice to be able to use `lowerCamelCase` for everything in TypeScript.

**Comment by Perryvw** [comment]
If your declarations use PacalCase just do everything in PascalCase, we will not be adding a renaming mechanism just because of user preference.
