### ISSUE TITLE
Add the Ability to extend native Lua classes/modules

### ISSUE THREAD

**Issue by lolleko** [Perryvw/TypescriptToLua#7]
Right now it is not possible to extend table (classes) or modules that already exist in Lua, the output would just overwrite them.

Examples use cases:
```
// classes
CDOTA_PlayerResource

// modules
table, math, os ...
```

I can think of 2 possible Solutions:

1. Find something, elegant similar to:

```
// Extend the type, and declare the new function
interface Date {
    getWeekNumber(): number;
}

// Add the implementation
Date.prototype.getWeekNumber = function () {
	return 1;
};
```

I don't know TS well enough to find something like this. But I don't think this will be possible at all because, CDOTA_PlayerResource for example only exists as type in TS when compiling, the value only exists in Lua.

2. Annotations

```
class testB extends /*luatable*/ testA {
}

// or

class testC /*luatable*/ {
}

// or for modules

class testD /*luamodule*/ {
}
```

**Comment by Perryvw** [comment]
Now possible with commit c964803b4956c07a6fe196ce94f235b2545c8e1a.

For interfaces (i.e PlayerResource) simply add a new interface declaration with the same name and they will merge.

For classes declare a new class and add the `/** !Extension */` flag, for example:
```
/** !Extension */
class entExt extends CBaseEntity {
    testFunc(arg: string): number {
        return 4;
    }
}
```

This will compile extending CBaseEntity with `CBaseEntity.testFunc(self, arg)`.
