### ISSUE TITLE
compilerOption: dontRequireLualib

### ISSUE THREAD

**Issue by Janne252** [Perryvw/TypescriptToLua#71]
First of all, this is an incredibly useful tool! Thank you so much for creating it.

A bit of background/thoughts before I start asking for things:
>I've been using lua for a bit over 6 years now (mainly as the scripting language for Company of Heroes >1 and 2). Lack of static types has been a limiting factor. 
>I'm aware therte are typed variants of Lua but those usually won't solve the other half of the problem: >Editor/IDE support. TypeScript has excellent support on VS Code which makes it the perfect **transpile->to-**<*insert language here*\> language. 

**The issue/request:**
Looks like the option [`dontRequireLualib`](https://github.com/Perryvw/TypescriptToLua/blob/master/src/Transpiler.ts#L34) is at least a planned feature since it works if you add it to the [tstlOptions](https://github.com/Perryvw/TypescriptToLua/blob/master/src/Compiler.ts#L132) configuration:

```typescript
        'dontRequireLualib': {
            alias: 'dontRequireLualib',
            describe: '',
            default: false,
            type: 'boolean'
        }
```
(Otherwise the process [gets terminated without specifying the reason](https://github.com/Perryvw/TypescriptToLua/blob/master/src/Compiler.ts#L126))

Looks like the most [recent pull request is about to touch the compiler options](https://github.com/Perryvw/TypescriptToLua/pull/70), perhaps this feature could be snuck in? I suppose I could submit a pull request for this too.

**Why?**
This is an important functionality in CoH1's/CoH2's enbedded & customized lua enviroment since the developers provided a custom function for importing libraries. The use case is extremely narrow but since it's 99% implemented, I thought I'd ask.

**Comment by lolleko** [comment]
It's currently used internally for testing.
I dont see a problem exposing it to the cli/config.
I will add it to the PR.

**Comment by Perryvw** [comment]
Just keep in mind that without the lib some functionality might not work. An optional workaround to this could be to maybe just put the used functions directly in the transpiled file if `dontRequireLuaLib` is used. What are your thoughts on that?

**Comment by Janne252** [comment]
Inline `typescript.lua` at the top of the file or inject lua code where the functionality from `typescript.lua` is used?

Some JavaScript transpilers inline extension functions in a similar fashion (if you plan to support `--outFile`, `--inlineLuaLib`/`--injectLuaLib` could be useful) but I think that only makes sense when the output is collected to a single file. Then again in some cases `--injectLuaLib` could be preferred.

My intention is to include the [`typescript.lua`](https://github.com/Perryvw/TypescriptToLua/blob/master/dist/lualib/typescript.lua)  manually because the system that I primarily develop lua for doesn't support `require` (as explained in the first post). 

For that reason being able to generate lua code without automatically generated `require` statements is important for me.

**Comment by Janne252** [comment]
Hey,

It seems that this is now mainly implemented with the exception of not being able to generate the bundle & NOT generate import statements.

Could `luaLibImport` be expanded with a 4th option, `manualImport`? (https://github.com/Perryvw/TypescriptToLua/pull/148)

When selected, the generated bundle would be created but no import statements would be added at the top of the files. Thanks!

**Comment by lolleko** [comment]
Moved to #155
