### ISSUE TITLE
why can't use 'do{}while();' grammar?

### ISSUE THREAD

**Issue by rifox** [Perryvw/TypescriptToLua#72]
1.why can't use 'do{}while();' grammar?
2.'switch' can't nest use..

sorry.I didn't mean to find trouble

**Comment by Perryvw** [comment]
I think `do{}while()` is just not supported yet right now, I can have a look at that later today. Can you give an example of the switch issue?

**Comment by rifox** [comment]
```typescript
class Test {
    Main() {
        let a = 0, b = 0;
        switch (a) {
            case 0:

                switch (b) {
                    case 0: console.log("hey imfox"); break;
                    default:
                }
                break;

            default:
        }
    }
}
new Test().Main();
```
just like this

**Comment by Perryvw** [comment]
Thank you, I will look into it!

**Comment by lolleko** [comment]
Seems to be caused by breaks not being ignored  in the nested switch, should be an easy fix.

**Comment by Perryvw** [comment]
Fixed nested while loops in 8e858b08a2a7e9ab479ed80b12b9013fdd3443ba, do {} while() is in #73 and will be added when the pull request is reviewed.

**Comment by Perryvw** [comment]
do while added as of 44da97f7ea5d5f227901c1c13df9baefb3e621c4

**Comment by rifox** [comment]
thank you for your help
