### ISSUE TITLE
tstl -p ./tsconfig.json throws error

### ISSUE THREAD

**Issue by ffgda** [Perryvw/TypescriptToLua#83]
Missing assignment to configPath in Line 165 of CommandLineParser.ts:

https://github.com/Perryvw/TypescriptToLua/blob/a4417ffebc11ce32af674c6c10f9e8f98139477e/src/CommandLineParser.ts#L165

**Comment by lolleko** [comment]
Should be fixed in  428c47c and will be in the next release
