### ISSUE TITLE
For-loop translations are inaccurate.

### ISSUE THREAD

**Issue by Perryvw** [Perryvw/TypescriptToLua#85]
Issue:
`for (let i = 0; i < n; i++)` and `for (let i = 0; i > n; i++)` translate to the same thing.

This indicates a pretty serious issue, we should probably rewrite ForHelper.ts

**Comment by dasannikov** [comment]
local i in output file do not have correct padding. Example:
``` Lua
function update(self,dt)
    gFpsCounter:update(dt)
local i = 0
    while(i<#unitList) do
        unitList[i+1]:update(dt)
        i=i+1
    end
end
```

**Comment by lolleko** [comment]
good catch didn't see that. should be fixed
