### ISSUE TITLE
Option to specify output file name

### ISSUE THREAD

**Issue by dasannikov** [Perryvw/TypescriptToLua#89]
Option to specify output file name.

```
$> tstl input1.ts -o output1.script
$> tstl input2.ts -o output2.script
```

**Comment by lolleko** [comment]
To quote the typescript deep dive book:

> --outFile is really the job of some build tool.

https://basarat.gitbooks.io/typescript/docs/tips/outFile.html

We will add support for this but it will be limited and probably only work when you compile a single file.
If something more advanced is needed, a build tool should be used.

Syntax will be:

`tstl --outFile test.script test.ts`

**Comment by dasannikov** [comment]
Nice!.
