### ISSUE TITLE
Any way to add additional lua code to output file.

### ISSUE THREAD

**Issue by dasannikov** [Perryvw/TypescriptToLua#90]
Basically I need to add my lua library to output lua file. It lead to universal way - use special comments. Any lua code from this TypeScript comments will go to output file.

TypeScript:

``` TypeScript
//@lua require("mylualib")

//@lua function delete_script()
//@lua   print("Delete script")   
//@lua   delete()
//@lua end

declare function delete_script(): void

mylualib_function()
delete_script()

```
Output Lua:

``` Lua
require("typescript_lualib")

require("mylualib")
function delete_script()
  print("Delete script")   
  delete()
end

mylualib_function()
delete_script()

```

**Comment by lolleko** [comment]
We support most import/exports statements:

```
// test.ts
export class TestClass {
    memberFunc() {}
}
```
Possible ways to import:
```
import * as Test from "./test.ts"
```
```
import {TestClass} from "./test.ts"
```
```
import {TestClass as RenamedClass} from "test"
```

**Comment by dasannikov** [comment]
Yes it works for my own TYpeScript code, but no way to import and use third-party lua libraries.

**Comment by Perryvw** [comment]
I would simply add `require(file: string)` to your declarations and add that to your typescript code.

**Comment by dasannikov** [comment]
Yes, require() keyword will work.
