### ISSUE TITLE
Namespace transpilation incorrect

### ISSUE THREAD

**Issue by Aeomi** [Perryvw/TypescriptToLua#94]
When transpiling a Typescript namespace that contains functions the resulting Lua does not correctly set their access to local.

Example:
![image](https://i.imgur.com/bLqQrGZ.png)
Generates to:
![image](https://user-images.githubusercontent.com/5202641/38713949-e7a9dbbe-3ea1-11e8-9956-1e30c4e78f99.png)

The generated Lua defines the namespaces' functions globally, they should each be local within the closure.

**Comment by Perryvw** [comment]
Fixed with c778b3c4d72ac2f97c34306aef2528a3fd1e3bb5 (v0.1.4)
