### ISSUE TITLE
No transpilation for spread operator

### ISSUE THREAD

**Issue by Aeomi** [Perryvw/TypescriptToLua#95]
As titled; example as follows:

![image](https://user-images.githubusercontent.com/5202641/38783970-781e3ec8-40d8-11e8-9581-ad6d1975f207.png)

![image](https://user-images.githubusercontent.com/5202641/38783971-8c664ede-40d8-11e8-8d04-1be6e01b4132.png)

As you can see, `rest => 'a'` which will result in an error.

I have fixed this issue in a subset project of TSTL. However, I cannot perform a pull request as my subset is too far removed from TSTL at this point.

**Comment by Aeomi** [comment]
I believe this is incorrectly labeled, this is most certainly an error in transpilation. The use of the '(...varargs: T)' does not transpile to lua's varargs, as you can see it transpiles to normal variable which is erroneous.

**Comment by lolleko** [comment]
How did you resolve the issue?

**Comment by Aeomi** [comment]
I'll re-write the solution for tstl and send in a pull request with the issue fixed
