### ISSUE TITLE
Undefined names for 0.1.1-0.1.4

### ISSUE THREAD

**Issue by Timur2915** [Perryvw/TypescriptToLua#96]
Last versions produce incorrect Lua code after transpilation with undefined instead variables/functions/etc names.

TypeScript code to reproduce:
```typescript
class ClassA {}
class ClassB extends ClassA {}

let a = 1;
let b = 2;
let c = a + b;
```

Code produced after transpilation (0.1.4 version):
```lua
-- Generated by TypescriptToLua v0.1.4
-- https://github.com/Perryvw/TypescriptToLua
require("typescript_lualib")
undefined = undefined or {}
undefined.__index = undefined
function undefined.new(construct, ...)
    local instance = setmetatable({}, undefined)
    if construct and undefined.constructor then undefined.constructor(instance, ...) end
    return instance
end
function undefined.constructor(self)
end
undefined = undefined or undefined.new()
undefined.__index = undefined
undefined.__base = undefined
function undefined.new(construct, ...)
    local instance = setmetatable({}, undefined)
    if construct and undefined.constructor then undefined.constructor(instance, ...) end
    return instance
end
function undefined.constructor(self)
end
local undefined = 1

local undefined = 2

local undefined = a+b
```
It's clean installation by usage guide section of readme. On 0.1.0 it works as expected.
Node version: 9.3.0.

**Comment by lolleko** [comment]
Can't reproduce with your example, this is especially weird since 0.1.1 was mostly testing and refactoring. I will have do to some further digging.

**Comment by Perryvw** [comment]
I am also not able to reproduce this, also tests in our continuous integration are passing. How are you running the transpiler?

**Comment by Timur2915** [comment]
My fault, it was 2.4.1, after updating to latest everything is alright. Thanks for reply. I think you need to add some requirements/FAQ.

**Comment by lolleko** [comment]
Typescript should probably be moved from devDependecies to dependencies, this should force the download of the correct ts version.

**Comment by Perryvw** [comment]
Made the move with b54ecd1fa61f47b35b54be98c116277a9b01dfa6
